/*
Navicat MySQL Data Transfer

Source Server         : Lokak (xampp)
Source Server Version : 50505
Source Host           : localhost:3306
Source Database       : characters

Target Server Type    : MYSQL
Target Server Version : 50505
File Encoding         : 65001

Date: 2019-05-30 02:05:35
*/

SET FOREIGN_KEY_CHECKS=0;
-- ----------------------------
-- Table structure for `dbdocsfields`
-- ----------------------------
DROP TABLE IF EXISTS `dbdocsfields`;
CREATE TABLE `dbdocsfields` (
  `fieldId` int(11) NOT NULL AUTO_INCREMENT COMMENT 'Unique Id for this field',
  `languageId` int(11) NOT NULL DEFAULT '0' COMMENT 'dbdocsLanguageId to link to. (Normallu 0 = English)',
  `tableName` varchar(80) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Name of the table to link to',
  `fieldName` varchar(80) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Name of the field to link the note to',
  `fieldComment` varchar(80) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Main field Note',
  `fieldNotes` text COLLATE utf8_unicode_ci NOT NULL COMMENT 'Additional Field Notes',
  PRIMARY KEY (`fieldId`,`languageId`),
  KEY `fieldId` (`fieldId`)
) ENGINE=InnoDB AUTO_INCREMENT=378 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- ----------------------------
-- Records of dbdocsfields
-- ----------------------------
INSERT INTO `dbdocsfields` VALUES ('1', '0', 'account', 'expansion', 'Which expansion\'s content a user has access to.', 'The field controls to which expansion\'s content a user has access. By default this is set to 0, allowing access to vanilla WoW content. In mangos-zero, other values can be ignored, since there is no expansion.<br />\r\n');
INSERT INTO `dbdocsfields` VALUES ('2', '0', 'auction', 'auctioneerguid', 'The GUID of the creature where the auction item was added. (See creature.guid)', 'The GUID of the creature where the auction item was added. (See creature.guid)');
INSERT INTO `dbdocsfields` VALUES ('3', '0', 'auction', 'buyguid', 'The GUID of the highest bidder. See (character.guid)', 'The GUID of the highest bidder. See (character.guid)');
INSERT INTO `dbdocsfields` VALUES ('4', '0', 'auction', 'buyoutprice', 'The buyout price of the item in copper.', 'The buyout price of the item in copper. Divide by 100 to get silver and by 100 again to get gold.');
INSERT INTO `dbdocsfields` VALUES ('5', '0', 'auction', 'deposit', 'The amount of copper spent on the deposit.', 'The amount of copper spent on the deposit.');
INSERT INTO `dbdocsfields` VALUES ('6', '0', 'auction', 'houseid', 'The AuctionHouseId (See AuctionHouse.dbc)', 'The AuctionHouseId (See AuctionHouse.dbc)');
INSERT INTO `dbdocsfields` VALUES ('7', '0', 'auction', 'id', 'Unique identifier for every auction.', 'Unique identifier for every auction.');
INSERT INTO `dbdocsfields` VALUES ('8', '0', 'auction', 'item_count', 'The stack count of the item', 'The stack count of the item');
INSERT INTO `dbdocsfields` VALUES ('9', '0', 'auction', 'item_randompropertyid', 'A link to the Item\'s RandomProperty Id (See item_template.Randompropertyid).', 'A link to the Item\'s RandomProperty Id (See item_template.Randompropertyid).');
INSERT INTO `dbdocsfields` VALUES ('10', '0', 'auction', 'item_template', 'The entry of the item up for auction. See (item_template.entry)', 'The entry of the item up for auction. See (item_template.entry)');
INSERT INTO `dbdocsfields` VALUES ('11', '0', 'auction', 'itemguid', 'The GUID of the item that is up for auction. (See item_instance.guid)', 'The GUID of the item that is up for auction. (See item_instance.guid)');
INSERT INTO `dbdocsfields` VALUES ('12', '0', 'auction', 'itemowner', 'The GUID of the owner of the item up for auction. (See character.guid)', 'The GUID of the owner of the item up for auction. (See character.guid)');
INSERT INTO `dbdocsfields` VALUES ('13', '0', 'auction', 'lastbid', 'The amount of copper of the last bid made on the item.', 'The amount of copper of the last bid made on the item.');
INSERT INTO `dbdocsfields` VALUES ('14', '0', 'auction', 'startbid', 'The amount of copper of the starting bid made on the item.', 'The amount of copper of the starting bid made on the item.');
INSERT INTO `dbdocsfields` VALUES ('15', '0', 'auction', 'time', 'The time when this auction will end, measured in Unix time.', 'The time when this auction will end, measured in Unix time (number of seconds from 00:00 Jan 1, 1970).');
INSERT INTO `dbdocsfields` VALUES ('16', '0', 'bugreport', 'content', 'The text content of the bug/suggestion.', 'The text content of the bug/suggestion.');
INSERT INTO `dbdocsfields` VALUES ('17', '0', 'bugreport', 'id', 'Auto generated value when records are inserted by the core.', 'Auto generated value when records are inserted by the core. This id is just here to be a primary key and eases the data insertion. This field is also a auto increment field');
INSERT INTO `dbdocsfields` VALUES ('18', '0', 'bugreport', 'type', 'The text description of the type of bug report / suggestion.', 'The text description of the type of bug report / suggestion.');
INSERT INTO `dbdocsfields` VALUES ('19', '0', 'character_action', 'action', 'Depending on the type value, this could be various values.', 'Depending on the type value, this could be either the spell ID (Spell.dbc), the item_template.entry or macro ID.');
INSERT INTO `dbdocsfields` VALUES ('20', '0', 'character_action', 'button', 'The ID of the button on the action bar where the action icon will be placed.', 'The ID of the button on the action bar where the action icon will be placed.<br />\r\nSpecial bars are used for stances, auras, pets, stealth, and other similar special modes.<br />\r\n\r\n');
INSERT INTO `dbdocsfields` VALUES ('21', '0', 'character_action', 'guid', 'The GUID of the character (See character.id).', 'The GUID of the character. (See character.id)');
INSERT INTO `dbdocsfields` VALUES ('22', '0', 'character_action', 'type', 'The type of action.', 'The type of action:<br />\r\n');
INSERT INTO `dbdocsfields` VALUES ('23', '0', 'character_aura', 'basepoints0', 'zzzz', 'zzzz');
INSERT INTO `dbdocsfields` VALUES ('24', '0', 'character_aura', 'basepoints1', 'zzzz', 'zzzz');
INSERT INTO `dbdocsfields` VALUES ('25', '0', 'character_aura', 'basepoints2', 'zzzz', 'zzzz');
INSERT INTO `dbdocsfields` VALUES ('26', '0', 'character_aura', 'caster_guid', 'The GUID (Global Unique Identifier) of the player who cast the aura.', 'The GUID (Global Unique Identifier) of the player who cast the aura. (See character.id).');
INSERT INTO `dbdocsfields` VALUES ('27', '0', 'character_aura', 'effIndexMask', 'The effect index of the spell from which the aura came from.', 'The effect index of the spell from which the aura came from. A spell has up to three effects, with the index being 0, 1, or 2.');
INSERT INTO `dbdocsfields` VALUES ('28', '0', 'character_aura', 'guid', 'The GUID (Full Global Unique Identifier) of the target affected by the aura.', 'The GUID (Full Global Unique Identifier) of the target affected by the aura. (See character.id).');
INSERT INTO `dbdocsfields` VALUES ('29', '0', 'character_aura', 'item_guid', 'The GUID (Global Unique Identifier) of the item which casted the aura.', 'The GUID (Global Unique Identifier) of the item which casted the aura. (See item_instance.guid).');
INSERT INTO `dbdocsfields` VALUES ('30', '0', 'character_aura', 'maxduration', 'The maximum duration of the aura.', 'The maximum duration of the aura.');
INSERT INTO `dbdocsfields` VALUES ('31', '0', 'character_aura', 'periodictime0', 'zzzz', 'zzzz');
INSERT INTO `dbdocsfields` VALUES ('32', '0', 'character_aura', 'periodictime1', 'zzzz', 'zzzz');
INSERT INTO `dbdocsfields` VALUES ('33', '0', 'character_aura', 'periodictime2', 'zzzz', 'zzzz');
INSERT INTO `dbdocsfields` VALUES ('34', '0', 'character_aura', 'remaincharges', 'The number of charges remaining on the aura.', 'The number of charges remaining on the aura.');
INSERT INTO `dbdocsfields` VALUES ('35', '0', 'character_aura', 'remainingcharges', 'zzzz', 'zzzz');
INSERT INTO `dbdocsfields` VALUES ('36', '0', 'character_aura', 'remaintime', 'The time remaining in seconds on the aura. -1 means that the aura is indefinite.', 'The time remaining in seconds on the aura. -1 means that the aura is indefinite.');
INSERT INTO `dbdocsfields` VALUES ('37', '0', 'character_aura', 'spell', 'The spell from which the aura was applied. (See Spell.dbc)', 'The spell from which the aura was applied. (See Spell.dbc column 1)');
INSERT INTO `dbdocsfields` VALUES ('38', '0', 'character_aura', 'stackcount', 'Determines how many stacks of the spell the character has.', 'Determines how many stacks of the spell the character has.');
INSERT INTO `dbdocsfields` VALUES ('39', '0', 'character_battleground_data', 'guid', 'zzzz', 'zzzz');
INSERT INTO `dbdocsfields` VALUES ('40', '0', 'character_battleground_data', 'instance_id', 'zzzz', 'zzzz');
INSERT INTO `dbdocsfields` VALUES ('41', '0', 'character_battleground_data', 'join_map', 'zzzz', 'zzzz');
INSERT INTO `dbdocsfields` VALUES ('42', '0', 'character_battleground_data', 'join_o', 'zzzz', 'zzzz');
INSERT INTO `dbdocsfields` VALUES ('43', '0', 'character_battleground_data', 'join_x', 'zzzz', 'zzzz');
INSERT INTO `dbdocsfields` VALUES ('44', '0', 'character_battleground_data', 'join_y', 'zzzz', 'zzzz');
INSERT INTO `dbdocsfields` VALUES ('45', '0', 'character_battleground_data', 'join_z', 'zzzz', 'zzzz');
INSERT INTO `dbdocsfields` VALUES ('46', '0', 'character_battleground_data', 'team', 'zzzz', 'zzzz');
INSERT INTO `dbdocsfields` VALUES ('47', '0', 'character_db_version', 'required_20000_Release_019_Initial', 'The Version of the Character DB.', 'The Version of the Character DB.');
INSERT INTO `dbdocsfields` VALUES ('48', '0', 'character_gifts', 'entry', 'The entry of the item. (See item_template.entry).', 'The entry of the item. (See item_template.entry).');
INSERT INTO `dbdocsfields` VALUES ('49', '0', 'character_gifts', 'flags', 'zzzz', 'zzzz');
INSERT INTO `dbdocsfields` VALUES ('50', '0', 'character_gifts', 'guid', 'The GUID (Global Unique Identifier) of the character. (See character.guid).', 'The GUID (Global Unique Identifier) of the character. (See character.guid).');
INSERT INTO `dbdocsfields` VALUES ('51', '0', 'character_gifts', 'item_guid', 'The GUID of the item. (See item_instance.guid).', 'The GUID of the item. (See item_instance.guid).');
INSERT INTO `dbdocsfields` VALUES ('52', '0', 'character_homebind', 'guid', 'The GUID (Global Unique Identifier) of the character. (See character.guid).', 'The GUID (Global Unique Identifier) of the character. (See character.guid).');
INSERT INTO `dbdocsfields` VALUES ('53', '0', 'character_homebind', 'map', 'The Map Identifier where the character gets teleported to. (See Maps.dbc).', 'The Map Identifier where the character gets teleported to (See Maps.dbc).');
INSERT INTO `dbdocsfields` VALUES ('54', '0', 'character_homebind', 'position_x', 'The x position where the character gets teleported to.', 'The x position where the character gets teleported to.');
INSERT INTO `dbdocsfields` VALUES ('55', '0', 'character_homebind', 'position_y', 'The y position where the character gets teleported to.', 'The y position where the character gets teleported to.');
INSERT INTO `dbdocsfields` VALUES ('56', '0', 'character_homebind', 'position_z', 'The z position where the character gets teleported to.', 'The z position where the character gets teleported to.');
INSERT INTO `dbdocsfields` VALUES ('57', '0', 'character_homebind', 'zone', 'The Zone Identifier where the character gets teleported to.', 'The zone ID (Zone Identifier) where the character gets teleported to (See WorldMapArea.dbc).');
INSERT INTO `dbdocsfields` VALUES ('58', '0', 'character_honor_cp', 'date', 'zzzz', 'zzzz');
INSERT INTO `dbdocsfields` VALUES ('59', '0', 'character_honor_cp', 'guid', 'zzzz', 'zzzz');
INSERT INTO `dbdocsfields` VALUES ('60', '0', 'character_honor_cp', 'honor', 'zzzz', 'zzzz');
INSERT INTO `dbdocsfields` VALUES ('61', '0', 'character_honor_cp', 'type', 'zzzz', 'zzzz');
INSERT INTO `dbdocsfields` VALUES ('62', '0', 'character_honor_cp', 'victim', 'zzzz', 'zzzz');
INSERT INTO `dbdocsfields` VALUES ('63', '0', 'character_honor_cp', 'victim_type', 'zzzz', 'zzzz');
INSERT INTO `dbdocsfields` VALUES ('64', '0', 'character_instance', 'guid', 'The GUID (Global Unique Identifier) of the character.', 'The GUID (Global Unique Identifier) of the character (See character.guid).');
INSERT INTO `dbdocsfields` VALUES ('65', '0', 'character_instance', 'instance', 'The instance ID. (See instance.id).', 'The instance ID. (See instance.id).');
INSERT INTO `dbdocsfields` VALUES ('66', '0', 'character_instance', 'permanent', 'Boolean 0 or 1 controlling if the player has been bound to the instance.', 'Boolean 0 or 1 controlling if the player has been bound to the instance. \r\nA player is bound to the instance only when he (or his party/raid) kills a creature with the CREATURE_FLAG_EXTRA_INSTANCE_BIND flag set in the (creature_template.flags_extra) field.');
INSERT INTO `dbdocsfields` VALUES ('67', '0', 'character_inventory', 'bag', 'If it isn\'t 0, then it is the bag\'s item GUID (Global Unique Identifier).', 'If it isn\'t 0, then it is the bag\'s item GUID (Global Unique Identifier). (See item_instance.guid).');
INSERT INTO `dbdocsfields` VALUES ('68', '0', 'character_inventory', 'guid', 'The GUID (Global Unique Identifier) of the character. (See character.guid).', 'The GUID (Global Unique Identifier) of the character. (See character.guid).');
INSERT INTO `dbdocsfields` VALUES ('69', '0', 'character_inventory', 'item', 'The item\'s GUID. (See item_instance.guid).', 'The item\'s GUID. (See item_instance.guid).');
INSERT INTO `dbdocsfields` VALUES ('70', '0', 'character_inventory', 'item_template', 'The item\'s template entry (Item Identifier). (See item_template.entry).', 'The item\'s template entry (Item Identifier). (See item_template.entry).');
INSERT INTO `dbdocsfields` VALUES ('71', '0', 'character_inventory', 'slot', 'The slot is the slot in the bag where the item is.', 'If the bag field is non-zero, then the slot is the slot in the bag where the item is kept. The range can differ depending on the number of slots the bag has.<br />\r\nIf the bag field is zero, then the slot has a range of 0 to 84 and the value stands for the following:<br />\r\n\r\n');
INSERT INTO `dbdocsfields` VALUES ('72', '0', 'character_pet', 'abdata', 'Data about pet action bar and action type ten pairs of action bar entry.', 'data about pet action bar and action type ten pairs of action bar entry (from 1 to 10) and action or spell IDs');
INSERT INTO `dbdocsfields` VALUES ('73', '0', 'character_pet', 'CreatedBySpell', 'The ID of the spell that has created this pet.', 'The ID of the spell that has created this pet. \r\nFor hunters, this is usually the Tame Beast spell. \r\nFor warlocks or other classes (mages), it is the spell ID that summoned the creature. (See Spell.dbc column 1)');
INSERT INTO `dbdocsfields` VALUES ('74', '0', 'character_pet', 'curhappiness', 'The current pet happiness.', 'The current pet happiness.');
INSERT INTO `dbdocsfields` VALUES ('75', '0', 'character_pet', 'curhealth', 'The current pet health at the time it was saved to DB.', 'The current pet health at the time it was saved to DB.');
INSERT INTO `dbdocsfields` VALUES ('76', '0', 'character_pet', 'curmana', 'The current pet mana at the time it was saved to DB.', 'The current pet mana at the time it was saved to DB.');
INSERT INTO `dbdocsfields` VALUES ('77', '0', 'character_pet', 'entry', 'The creature entry of this pet. (See creature_template.entry).', 'The creature entry of this pet. (See creature_template.entry).');
INSERT INTO `dbdocsfields` VALUES ('78', '0', 'character_pet', 'exp', 'The current experience that this pet has.', 'The current experience that this pet has. For summoned pets, this field is always 0.');
INSERT INTO `dbdocsfields` VALUES ('79', '0', 'character_pet', 'id', 'The special pet ID. This is a unique identifier among all pets.', 'The special pet ID. This is a unique identifier among all pets.');
INSERT INTO `dbdocsfields` VALUES ('80', '0', 'character_pet', 'level', 'The current level of the pet.', 'The current level of the pet.');
INSERT INTO `dbdocsfields` VALUES ('81', '0', 'character_pet', 'loyalty', 'zzzz', 'zzzz');
INSERT INTO `dbdocsfields` VALUES ('82', '0', 'character_pet', 'loyaltypoints', 'zzzz', 'zzzz');
INSERT INTO `dbdocsfields` VALUES ('83', '0', 'character_pet', 'modelid', 'The model ID to use to display the pet.', 'The model ID to use to display the pet.');
INSERT INTO `dbdocsfields` VALUES ('84', '0', 'character_pet', 'name', 'The pet\'s name.', 'The pet\'s name.');
INSERT INTO `dbdocsfields` VALUES ('85', '0', 'character_pet', 'owner', 'The GUID of the pet\'s owner. (See character.guid).', 'The GUID of the pet\'s owner. (See character.guid).');
INSERT INTO `dbdocsfields` VALUES ('86', '0', 'character_pet', 'PetType', 'The type of pet that this is. 0 = summoned pet, 1 = tamed pet', 'The type of pet that this is. 0 = summoned pet, 1 = tamed pet');
INSERT INTO `dbdocsfields` VALUES ('87', '0', 'character_pet', 'Reactstate', 'The current reaction state of the pet (passive, aggressive, etc).', 'The current reaction state of the pet (passive, aggressive, etc).');
INSERT INTO `dbdocsfields` VALUES ('88', '0', 'character_pet', 'renamed', 'Boolean 1 or 0. 1 = Pet has been renamed.', 'Boolean 1 or 0. 1 = Pet has been renamed, 0 = Pet has never been renamed and still uses the same name as the creature that was tamed.');
INSERT INTO `dbdocsfields` VALUES ('89', '0', 'character_pet', 'resettalents_cost', 'This is the cost to \"untrain\" the pet talents.', 'This is the cost to \"untrain\" the pet talents.');
INSERT INTO `dbdocsfields` VALUES ('90', '0', 'character_pet', 'resettalents_time', 'How many times the pets talents have been reset.', 'How many times the pets talents have been reset.');
INSERT INTO `dbdocsfields` VALUES ('91', '0', 'character_pet', 'savetime', 'The time when the pet was last saved, in Unix time.', 'The time when the pet was last saved, in Unix time.');
INSERT INTO `dbdocsfields` VALUES ('92', '0', 'character_pet', 'slot', 'The pet slot that the pet is in. The slot is a number between 0 and 3 inclusive.', 'The pet slot that the pet is in. The slot is a number between 0 and 3 inclusive.');
INSERT INTO `dbdocsfields` VALUES ('93', '0', 'character_pet', 'teachspelldata', 'This field holds IDs of spells that have been taught to this pet.', 'This field holds IDs of spells that have been taught to this pet, abilities that this pet has.');
INSERT INTO `dbdocsfields` VALUES ('94', '0', 'character_pet', 'trainpoint', 'zzzz', 'zzzz');
INSERT INTO `dbdocsfields` VALUES ('95', '0', 'character_queststatus', 'explored', 'Boolean 1 or 0 representing if the character has explored what was needed.', 'Boolean 1 or 0 representing if the character has explored what was needed to explore for the quest.');
INSERT INTO `dbdocsfields` VALUES ('96', '0', 'character_queststatus', 'guid', 'The GUID of the character. (See character.guid).', 'The GUID of the character. (See character.guid).');
INSERT INTO `dbdocsfields` VALUES ('97', '0', 'character_queststatus', 'itemcount1', 'Current item count for the first item in a delivery quest, if any.', 'Current item count for the first item in a delivery quest, if any. Corresponds with quest_template.ReqItemCount1');
INSERT INTO `dbdocsfields` VALUES ('98', '0', 'character_queststatus', 'itemcount2', 'Current item count for the second item in a delivery quest, if any.', 'Current item count for the second item in a delivery quest, if any. Corresponds with quest_template.ReqItemCount2');
INSERT INTO `dbdocsfields` VALUES ('99', '0', 'character_queststatus', 'itemcount3', 'Current item count for the third item in a delivery quest, if any.', 'Current item count for the third item in a delivery quest, if any. Corresponds with quest_template.ReqItemCount3');
INSERT INTO `dbdocsfields` VALUES ('100', '0', 'character_queststatus', 'itemcount4', 'Current item count for the forth item in a delivery quest, if any.', 'Current item count for the forth item in a delivery quest, if any. Corresponds with quest_template.ReqItemCount4');
INSERT INTO `dbdocsfields` VALUES ('101', '0', 'character_queststatus', 'mobcount1', 'Current count of the first number of kills or casts.', 'Current count of the number of kills or casts on the second creature or gameobject, if any. Corresponds with quest_template.ReqCreatureOrGOCount1');
INSERT INTO `dbdocsfields` VALUES ('102', '0', 'character_queststatus', 'mobcount2', 'Current count of the second number of kills or casts.', 'Current count of the number of kills or casts on the second creature or gameobject, if any. Corresponds with quest_template.ReqCreatureOrGOCount2');
INSERT INTO `dbdocsfields` VALUES ('103', '0', 'character_queststatus', 'mobcount3', 'Current count of the third number of kills or casts.', 'Current count of the number of kills or casts on the third creature or gameobject, if any. Corresponds with quest_template.ReqCreatureOrGOCount3');
INSERT INTO `dbdocsfields` VALUES ('104', '0', 'character_queststatus', 'mobcount4', 'Current count of the forth number of kills or casts.', 'Current count of the number of kills or casts on the forth creature or gameobject, if any. Corresponds with quest_template.ReqCreatureOrGOCount4');
INSERT INTO `dbdocsfields` VALUES ('105', '0', 'character_queststatus', 'quest', 'The quest ID. (See quest_template.entry).', 'The quest ID. (See quest_template.entry).');
INSERT INTO `dbdocsfields` VALUES ('106', '0', 'character_queststatus', 'rewarded', 'Boolean 1 or 0 representing whether the quest has been rewarded or not.', 'Boolean 1 or 0 representing whether the quest has been rewarded or not.');
INSERT INTO `dbdocsfields` VALUES ('107', '0', 'character_queststatus', 'status', 'The current quest status.\r\n\r\n', 'The current quest status.<br />\r\n\r\n');
INSERT INTO `dbdocsfields` VALUES ('108', '0', 'character_queststatus', 'timer', 'Remaining time left on the quest if the quest has a timer (See quest_template).', 'Remaining time left on the quest if the quest has a timer. (See quest_template.LimitTime).');
INSERT INTO `dbdocsfields` VALUES ('109', '0', 'character_reputation', 'faction', 'The faction ID that the character has the given reputation in (See Faction.dbc).', 'The faction ID that the character has the given reputation in. (See Faction.dbc).');
INSERT INTO `dbdocsfields` VALUES ('110', '0', 'character_reputation', 'flags', 'This field is a bitmask containing flags that apply to the faction.', 'This field is a bitmask containing flags that apply to the faction and how it\'s displayed to the character. Just like any flag field, you can combine flags by adding them together. \r\nIf this field is 0, then it is not shown in the reputation list in-game.<br />\r\n\r\n');
INSERT INTO `dbdocsfields` VALUES ('111', '0', 'character_reputation', 'guid', 'The GUID of the character. (See character.guid).', 'The GUID of the character. (See character.guid).');
INSERT INTO `dbdocsfields` VALUES ('112', '0', 'character_reputation', 'standing', 'The current reputation value that the character has.', 'The current reputation value that the character has.');
INSERT INTO `dbdocsfields` VALUES ('113', '0', 'character_skills', 'guid', 'The GUID (Global Unique Identifier) of the character. (See character.guid).', 'The GUID (Global Unique Identifier) of the character. (See character.guid).');
INSERT INTO `dbdocsfields` VALUES ('114', '0', 'character_skills', 'max', 'The highest possible value for the given skill within a given rank.', 'The highest possible value for the given skill within a given rank.');
INSERT INTO `dbdocsfields` VALUES ('115', '0', 'character_skills', 'skill', 'The list of skills a character knows. A listing of those can be found in here.', 'The list of skills a character knows. A listing of those can be found in here.');
INSERT INTO `dbdocsfields` VALUES ('116', '0', 'character_skills', 'value', 'The current skill rank(value) of the character skills a character has.', 'The current skill rank(value) of the character skills a character has.');
INSERT INTO `dbdocsfields` VALUES ('117', '0', 'character_social', 'flags', 'Whether the character is a friend or ignored.', 'The flag indicating whether the entry is either a friend or ignored.<br />\r\n\r\n');
INSERT INTO `dbdocsfields` VALUES ('118', '0', 'character_social', 'friend', 'The GUID of the friend/ignored. (See character.guid)', 'The GUID of the friend/ignored. (See character.guid)');
INSERT INTO `dbdocsfields` VALUES ('119', '0', 'character_social', 'guid', 'The GUID of the character. (See character.guid)', 'The GUID of the character. (See character.guid)');
INSERT INTO `dbdocsfields` VALUES ('120', '0', 'character_spell', 'active', 'Boolean 1 or 0 signifying whether the spell is active (appears in the spell book', 'Boolean 1 or 0 signifying whether the spell is active (appears in the spell book).');
INSERT INTO `dbdocsfields` VALUES ('121', '0', 'character_spell', 'disabled', 'Boolean flag 0 or 1 when spell is disabled because of talents.', 'Boolean flag 0 or 1 when spell is disabled because talent which teaches it has been unlearned. When talent is learned again the spell will be available again.');
INSERT INTO `dbdocsfields` VALUES ('122', '0', 'character_spell', 'guid', 'The GUID (Global Unique Identifier) of the character. (See character.guid).', 'The GUID (Global Unique Identifier) of the character. (See character.guid).');
INSERT INTO `dbdocsfields` VALUES ('123', '0', 'character_spell', 'spell', 'The spell ID (Spell Identifier). (See Spell.dbc)', 'The spell ID (Spell Identifier). (See Spell.dbc column 1)');
INSERT INTO `dbdocsfields` VALUES ('124', '0', 'character_spell_cooldown', 'guid', 'The GUID (Global Unique Identifier, Low part) of the character.', 'The GUID (Global Unique Identifier, Low part) of the character. (See character.guid)');
INSERT INTO `dbdocsfields` VALUES ('125', '0', 'character_spell_cooldown', 'item', 'If the spell was casted from an item, the item ID (Item Identifier).', 'If the spell was casted from an item, the item ID (Item Identifier). (See item_template.entry).');
INSERT INTO `dbdocsfields` VALUES ('126', '0', 'character_spell_cooldown', 'spell', 'The spell ID (Spell Identifier). (See Spell.dbc)', 'The spell ID (Spell Identifier). (See Spell.dbc column 1)');
INSERT INTO `dbdocsfields` VALUES ('127', '0', 'character_spell_cooldown', 'time', 'The time when the spell cooldown will finish, measured in Unix Time.', 'The time when the spell cooldown will finish, measured in Unix Time.');
INSERT INTO `dbdocsfields` VALUES ('128', '0', 'character_stats', 'agility', 'Character\'s current agility value', 'Character\'s current agility value');
INSERT INTO `dbdocsfields` VALUES ('129', '0', 'character_stats', 'armor', 'Character\'s current armor value.', 'Character\'s current armor value.');
INSERT INTO `dbdocsfields` VALUES ('130', '0', 'character_stats', 'attackPower', 'Character\'s current attackpower.', 'Character\'s current attackpower.');
INSERT INTO `dbdocsfields` VALUES ('131', '0', 'character_stats', 'blockPct', 'Character\'s current block chance', 'Character\'s current block chance');
INSERT INTO `dbdocsfields` VALUES ('132', '0', 'character_stats', 'critPct', 'Character\'s current crit chance.', 'Character\'s current crit chance.');
INSERT INTO `dbdocsfields` VALUES ('133', '0', 'character_stats', 'dodgePct', 'Character\'s current dodge chance.', 'Character\'s current dodge chance.');
INSERT INTO `dbdocsfields` VALUES ('134', '0', 'character_stats', 'guid', 'The guid of the character. (See character.guid).', 'The guid of the character. (See character.guid).');
INSERT INTO `dbdocsfields` VALUES ('135', '0', 'character_stats', 'intellect', 'Character\'s current intellect value.', 'Character\'s current intellect value.');
INSERT INTO `dbdocsfields` VALUES ('136', '0', 'character_stats', 'maxhealth', 'Maximum amount of health that the character has.', 'Maximum amount of health that the character has.');
INSERT INTO `dbdocsfields` VALUES ('137', '0', 'character_stats', 'maxpower1', 'Max Mana', 'Max Mana');
INSERT INTO `dbdocsfields` VALUES ('138', '0', 'character_stats', 'maxpower2', 'Max Rage', 'Max Rage');
INSERT INTO `dbdocsfields` VALUES ('139', '0', 'character_stats', 'maxpower3', 'Max Focus', 'Max Focus');
INSERT INTO `dbdocsfields` VALUES ('140', '0', 'character_stats', 'maxpower4', 'Max Energy', 'Max Energy');
INSERT INTO `dbdocsfields` VALUES ('141', '0', 'character_stats', 'maxpower5', 'Max Happiness', 'Max Happiness');
INSERT INTO `dbdocsfields` VALUES ('142', '0', 'character_stats', 'maxpower6', 'Max Rune', 'Max Rune');
INSERT INTO `dbdocsfields` VALUES ('143', '0', 'character_stats', 'maxpower7', 'Max Runic Power', 'Max Runic Power');
INSERT INTO `dbdocsfields` VALUES ('144', '0', 'character_stats', 'parryPct', 'Character\'s current parry chance.', 'Character\'s current parry chance.');
INSERT INTO `dbdocsfields` VALUES ('145', '0', 'character_stats', 'rangedAttackPower', 'Character\'s current ranged attackpower.', 'Character\'s current ranged attackpower.');
INSERT INTO `dbdocsfields` VALUES ('146', '0', 'character_stats', 'rangedCritPct', 'Character\'s current ranged crit chance.', 'Character\'s current ranged crit chance.');
INSERT INTO `dbdocsfields` VALUES ('147', '0', 'character_stats', 'resArcane', 'Character\'s current arcane resistance value.', 'Character\'s current arcane resistance value.');
INSERT INTO `dbdocsfields` VALUES ('148', '0', 'character_stats', 'resFire', 'Character\'s current fire resistance value.', 'Character\'s current fire resistance value.');
INSERT INTO `dbdocsfields` VALUES ('149', '0', 'character_stats', 'resFrost', 'Character\'s current frost resistance value.', 'Character\'s current frost resistance value.');
INSERT INTO `dbdocsfields` VALUES ('150', '0', 'character_stats', 'resHoly', 'Character\'s current holy resistance value.', 'Character\'s current holy resistance value.');
INSERT INTO `dbdocsfields` VALUES ('151', '0', 'character_stats', 'resNature', 'Character\'s current nature resistance value.', 'Character\'s current nature resistance value.');
INSERT INTO `dbdocsfields` VALUES ('152', '0', 'character_stats', 'resShadow', 'Character\'s current shadow resistance value.', 'Character\'s current shadow resistance value.');
INSERT INTO `dbdocsfields` VALUES ('153', '0', 'character_stats', 'spirit', 'Character\'s current spirit value.', 'Character\'s current spirit value.');
INSERT INTO `dbdocsfields` VALUES ('154', '0', 'character_stats', 'stamina', 'Character\'s current stamina value.', 'Character\'s current stamina value.');
INSERT INTO `dbdocsfields` VALUES ('155', '0', 'character_stats', 'strength', 'Character\'s current strength value.', 'Character\'s current strength value.');
INSERT INTO `dbdocsfields` VALUES ('156', '0', 'character_ticket', 'guid', 'The GUID of the character sending the ticket. (See character.guid).', 'The GUID of the character sending the ticket. (See character.guid).');
INSERT INTO `dbdocsfields` VALUES ('157', '0', 'character_ticket', 'resolved', 'Resolved Flag = set to 1 if the GM has sucessfully resolved the ticket', 'Resolved Flag = set to 1 if the GM has sucessfully resolved the ticket');
INSERT INTO `dbdocsfields` VALUES ('158', '0', 'character_ticket', 'response_text', 'The ticket solution text; the text written by the GM.', 'The ticket description text; the text written by the GM in describing the solution.');
INSERT INTO `dbdocsfields` VALUES ('159', '0', 'character_ticket', 'ticket_id', 'A unique ticket ID.', 'A unique ticket ID.');
INSERT INTO `dbdocsfields` VALUES ('160', '0', 'character_ticket', 'ticket_lastchange', 'Stores the time when this ticket was last changed.', 'Stores the time when this ticket was last changed.');
INSERT INTO `dbdocsfields` VALUES ('161', '0', 'character_ticket', 'ticket_text', 'The ticket description text; the text written by the player.', 'The ticket description text; the text written by the player in describing the problem.');
INSERT INTO `dbdocsfields` VALUES ('162', '0', 'character_tutorial', 'account', 'The account id of the user. (See account.id).', 'The account id of the user. (See account.id).');
INSERT INTO `dbdocsfields` VALUES ('163', '0', 'character_tutorial', 'tut0', 'These values are 32bits flags.', 'These values are 32bits flags. So 8 x 32bits values makes 256 bits available to store 256 tutorial messages status.\r\n\r\nEach bit means:\r\n\r\nbc.   0  -  Not yet shown\r\n  1  -  Shown\r\n\r\n\r\nThis is used to diplay only tutorial messages that the character did not see before.\r\n\r\nUnselecting the &quot;Show tutorial&quot; option in game, makes all bits to be set, so all tutX columns will contain then 11111111111111111111111111111111 binary = 4294967295 in decimal after this option is changed.\r\n');
INSERT INTO `dbdocsfields` VALUES ('164', '0', 'character_tutorial', 'tut1', 'These values are 32bits flags.', 'These values are 32bits flags. So 8 x 32bits values makes 256 bits available to store 256 tutorial messages status.\r\n\r\nEach bit means:\r\n\r\nbc.   0  -  Not yet shown\r\n  1  -  Shown\r\n\r\n\r\nThis is used to diplay only tutorial messages that the character did not see before.\r\n\r\nUnselecting the &quot;Show tutorial&quot; option in game, makes all bits to be set, so all tutX columns will contain then 11111111111111111111111111111111 binary = 4294967295 in decimal after this option is changed.\r\n');
INSERT INTO `dbdocsfields` VALUES ('165', '0', 'character_tutorial', 'tut2', 'These values are 32bits flags.', 'These values are 32bits flags. So 8 x 32bits values makes 256 bits available to store 256 tutorial messages status.\r\n\r\nEach bit means:\r\n\r\nbc.   0  -  Not yet shown\r\n  1  -  Shown\r\n\r\n\r\nThis is used to diplay only tutorial messages that the character did not see before.\r\n\r\nUnselecting the &quot;Show tutorial&quot; option in game, makes all bits to be set, so all tutX columns will contain then 11111111111111111111111111111111 binary = 4294967295 in decimal after this option is changed.\r\n');
INSERT INTO `dbdocsfields` VALUES ('166', '0', 'character_tutorial', 'tut3', 'These values are 32bits flags.', 'These values are 32bits flags. So 8 x 32bits values makes 256 bits available to store 256 tutorial messages status.\r\n\r\nEach bit means:\r\n\r\nbc.   0  -  Not yet shown\r\n  1  -  Shown\r\n\r\n\r\nThis is used to diplay only tutorial messages that the character did not see before.\r\n\r\nUnselecting the &quot;Show tutorial&quot; option in game, makes all bits to be set, so all tutX columns will contain then 11111111111111111111111111111111 binary = 4294967295 in decimal after this option is changed.\r\n');
INSERT INTO `dbdocsfields` VALUES ('167', '0', 'character_tutorial', 'tut4', 'These values are 32bits flags.', 'These values are 32bits flags. So 8 x 32bits values makes 256 bits available to store 256 tutorial messages status.\r\n\r\nEach bit means:\r\n\r\nbc.   0  -  Not yet shown\r\n  1  -  Shown\r\n\r\n\r\nThis is used to diplay only tutorial messages that the character did not see before.\r\n\r\nUnselecting the &quot;Show tutorial&quot; option in game, makes all bits to be set, so all tutX columns will contain then 11111111111111111111111111111111 binary = 4294967295 in decimal after this option is changed.\r\n');
INSERT INTO `dbdocsfields` VALUES ('168', '0', 'character_tutorial', 'tut5', 'These values are 32bits flags.', 'These values are 32bits flags. So 8 x 32bits values makes 256 bits available to store 256 tutorial messages status.\r\n\r\nEach bit means:\r\n\r\nbc.   0  -  Not yet shown\r\n  1  -  Shown\r\n\r\n\r\nThis is used to diplay only tutorial messages that the character did not see before.\r\n\r\nUnselecting the &quot;Show tutorial&quot; option in game, makes all bits to be set, so all tutX columns will contain then 11111111111111111111111111111111 binary = 4294967295 in decimal after this option is changed.\r\n');
INSERT INTO `dbdocsfields` VALUES ('169', '0', 'character_tutorial', 'tut6', 'These values are 32bits flags.', 'These values are 32bits flags. So 8 x 32bits values makes 256 bits available to store 256 tutorial messages status.\r\n\r\nEach bit means:\r\n\r\nbc.   0  -  Not yet shown\r\n  1  -  Shown\r\n\r\n\r\nThis is used to diplay only tutorial messages that the character did not see before.\r\n\r\nUnselecting the &quot;Show tutorial&quot; option in game, makes all bits to be set, so all tutX columns will contain then 11111111111111111111111111111111 binary = 4294967295 in decimal after this option is changed.\r\n');
INSERT INTO `dbdocsfields` VALUES ('170', '0', 'character_tutorial', 'tut7', 'These values are 32bits flags.', 'These values are 32bits flags. So 8 x 32bits values makes 256 bits available to store 256 tutorial messages status.\r\n\r\nEach bit means:\r\n\r\nbc.   0  -  Not yet shown\r\n  1  -  Shown\r\n\r\n\r\nThis is used to diplay only tutorial messages that the character did not see before.\r\n\r\nUnselecting the &quot;Show tutorial&quot; option in game, makes all bits to be set, so all tutX columns will contain then 11111111111111111111111111111111 binary = 4294967295 in decimal after this option is changed.\r\n');
INSERT INTO `dbdocsfields` VALUES ('171', '0', 'character_whispers', 'from_guid', 'The GUID of the character sending the whisper. (See character.guid).', 'The GUID of the character sending the whisper. (See character.guid).');
INSERT INTO `dbdocsfields` VALUES ('172', '0', 'character_whispers', 'id', 'The unique id of this whisper message', 'The unique id of this whisper message');
INSERT INTO `dbdocsfields` VALUES ('173', '0', 'character_whispers', 'message', 'The body text of the whisper message', 'The body text of the whisper message');
INSERT INTO `dbdocsfields` VALUES ('174', '0', 'character_whispers', 'regarding_ticket_id', 'The id of the ticket this whisper relates to. (See character_ticket.ticket_id).', 'The id of the ticket this whisper relates to. (See character_ticket.ticket_id).');
INSERT INTO `dbdocsfields` VALUES ('175', '0', 'character_whispers', 'sent_on', 'Stores the time when this whisper was sent.', 'Stores the time when this whisper was sent.');
INSERT INTO `dbdocsfields` VALUES ('176', '0', 'character_whispers', 'to_guid', 'The GUID of the character receiving the whisper. (See character.guid).', 'The GUID of the character receiving the whisper. (See character.guid).');
INSERT INTO `dbdocsfields` VALUES ('177', '0', 'characters', 'account', 'The account ID in which this character resides (See account.id) in the realm db.', 'The account ID in which this character resides. (See account.id) in the realm database.');
INSERT INTO `dbdocsfields` VALUES ('178', '0', 'characters', 'actionBars', 'actionbar\r\n\r\nList of entries that go on the pet-specific action bar.', 'actionbar\r\n\r\nList of entries that go on the pet-specific action bar (a.k.a. Pet Bar, Pet Action Bar). Entries are in the format: <actionid> <flags>,<actionid> <flags>,...,<actionid> <flags>\r\nFor example, a Hunter pet that is a low-level tamed cat might have an action bar that looks like this:\r\n<pre>\r\n    117440514 0,117440513 0,117440512 0,2649 33024,16827 33024,24450 33024,0 0,100663298 0,100663297 0,\r\n    <attack>     <follow>    <stay>     <Growl 1>  <Claw 1>    <Prowl 1>  <blank><aggress> <defens>\r\n</pre>\r\nEntries listed as \"0 0\" are blank slots on the action bar.');
INSERT INTO `dbdocsfields` VALUES ('179', '0', 'characters', 'ammoId', 'zzzz', 'zzzz');
INSERT INTO `dbdocsfields` VALUES ('180', '0', 'characters', 'at_login', 'The status of the character.\r\n\r\n', 'The status of the character.\r\n\r\n');
INSERT INTO `dbdocsfields` VALUES ('181', '0', 'characters', 'cinematic', 'Boolean 1 or 0 controlling whether the start cinematic has been shown or not.', 'Boolean 1 or 0 controlling whether the start cinematic has been shown or not.');
INSERT INTO `dbdocsfields` VALUES ('182', '0', 'characters', 'class', 'The Class Id of the character (See chrclasses.dbc).', 'The Class Id of the character (See chrclasses.dbc)');
INSERT INTO `dbdocsfields` VALUES ('183', '0', 'characters', 'death_expire_time', 'Time when a character can be resurrected.', 'Time when a character can be resurrected in case of a server crash or client exit while in ghost form.');
INSERT INTO `dbdocsfields` VALUES ('184', '0', 'characters', 'deleteDate', 'zzzz', 'zzzz');
INSERT INTO `dbdocsfields` VALUES ('185', '0', 'characters', 'deleteInfos_Account', 'zzzz', 'zzzz');
INSERT INTO `dbdocsfields` VALUES ('186', '0', 'characters', 'deleteInfos_Name', 'zzzz', 'zzzz');
INSERT INTO `dbdocsfields` VALUES ('187', '0', 'characters', 'drunk', 'zzzz', 'zzzz');
INSERT INTO `dbdocsfields` VALUES ('188', '0', 'characters', 'equipmentCache', 'zzzz', 'zzzz');
INSERT INTO `dbdocsfields` VALUES ('189', '0', 'characters', 'exploredZones', 'zzzz', 'zzzz');
INSERT INTO `dbdocsfields` VALUES ('190', '0', 'characters', 'extra_flags', 'These flags control certain player specific attributes, mostly GM features\r\n\r\n.', 'These flags control certain player specific attributes, mostly GM features\r\n\r\n<table border=\'1\' cellspacing=\'0\' cellpadding=\'4\' bgcolor=\'#f0f0f0\' width=\'100%\'>\r\n<tr bgcolor=\'#e0e0e0\'>\r\n<td align=\'center\' valign=\'middle\'><b>Bit</b></td>\r\n<td align=\'left\' valign=\'middle\'><b>Name</b></td>\r\n<td align=\'left\' valign=\'middle\'><b>Description</b></td>\r\n</tr>\r\n<tr>\r\n<td align=\'center\' valign=\'middle\'>1</td>\r\n<td align=\'left\' valign=\'middle\'>PLAYER&#95;EXTRA&#95;GM&#95;ON</td>\r\n<td align=\'left\' valign=\'middle\'>Defines GM state</td>\r\n</tr>\r\n<tr>\r\n<td align=\'center\' valign=\'middle\'>2</td>\r\n<td align=\'left\' valign=\'middle\'>PLAYER&#95;EXTRA&#95;GM&#95;ACCEPT&#95;TICKETS</td>\r\n<td align=\'left\' valign=\'middle\'>Defines if tickets are accepted</td>\r\n</tr>\r\n<tr>\r\n<td align=\'center\' valign=\'middle\'>4</td>\r\n<td align=\'left\' valign=\'middle\'>PLAYER&#95;EXTRA&#95;ACCEPT&#95;WHISPERS</td>\r\n<td align=\'left\' valign=\'middle\'>Defines if whispers are accepted</td>\r\n</tr>\r\n<tr>\r\n<td align=\'center\' valign=\'middle\'>8</td>\r\n<td align=\'left\' valign=\'middle\'>PLAYER&#95;EXTRA&#95;TAXICHEAT</td>\r\n<td align=\'left\' valign=\'middle\'>Sets taxicheat></td>\r\n</tr>\r\n<tr>\r\n<td align=\'center\' valign=\'middle\'>16</td>\r\n<td align=\'left\' valign=\'middle\'>PLAYER&#95;EXTRA&#95;GM&#95;INVISIBLE</td>\r\n<td align=\'left\' valign=\'middle\'>Control\'s GM\'s invisibly</td>\r\n</tr><tr>\r\n<td align=\'center\' valign=\'middle\'>32</td>\r\n<td align=\'left\' valign=\'middle\'>PLAYER&#95;EXTRA&#95;GM&#95;CHAT</td>\r\n<td align=\'left\' valign=\'middle\'>Show GM badge in chat messages</td>\r\n</tr><tr>\r\n<td align=\'center\' valign=\'middle\'>64</td>\r\n<td align=\'left\' valign=\'middle\'>PLAYER&#95;EXTRA&#95;PVP&#95;DEATH</td>\r\n<td align=\'left\' valign=\'middle\'>Store PvP death status until corpse creating</td>\r\n</tr></table>');
INSERT INTO `dbdocsfields` VALUES ('191', '0', 'characters', 'gender', 'The Sex/Gender of the character.', 'The Sex/Gender of the character.<br/>\r\n\r\n');
INSERT INTO `dbdocsfields` VALUES ('192', '0', 'characters', 'guid', 'The character global unique identifier.', 'The character global unique identifier. This number must be unique and is the best way to identify separate characters.');
INSERT INTO `dbdocsfields` VALUES ('193', '0', 'characters', 'health', 'zzzz', 'zzzz');
INSERT INTO `dbdocsfields` VALUES ('194', '0', 'characters', 'honor_highest_rank', 'zzzz', 'zzzz');
INSERT INTO `dbdocsfields` VALUES ('195', '0', 'characters', 'honor_standing', 'zzzz', 'zzzz');
INSERT INTO `dbdocsfields` VALUES ('196', '0', 'characters', 'is_logout_resting', 'Boolean 1 or 0 controlling if the character is currently in a resting zone.', 'Boolean 1 or 0 controlling if the character is currently in a resting zone or not.');
INSERT INTO `dbdocsfields` VALUES ('197', '0', 'characters', 'level', 'The current level of the designated player.', 'The current level of the designated player.');
INSERT INTO `dbdocsfields` VALUES ('198', '0', 'characters', 'leveltime', 'The total time the character has spent in the world at the current level.', 'The total time the character has spent in the world at the current level, measured in seconds.');
INSERT INTO `dbdocsfields` VALUES ('199', '0', 'characters', 'logout_time', 'The time when the character last logged out, measured in Unix time.', 'The time when the character last logged out, measured in Unix time.');
INSERT INTO `dbdocsfields` VALUES ('200', '0', 'characters', 'map', 'The map ID the character is in (See maps.dbc)', 'The map ID the character is in. (See maps.dbc)');
INSERT INTO `dbdocsfields` VALUES ('201', '0', 'characters', 'money', 'This is the amount of copper the character possesses.', 'This is the amount of copper the character possesses.');
INSERT INTO `dbdocsfields` VALUES ('202', '0', 'characters', 'name', 'The name of the character.', 'The name of the character.');
INSERT INTO `dbdocsfields` VALUES ('203', '0', 'characters', 'online', 'Records whether the character is online (1) or offline (0).', 'Records whether the character is online (1) or offline (0).');
INSERT INTO `dbdocsfields` VALUES ('204', '0', 'characters', 'orientation', 'The orientation the character is facing. (North = 0.0, South = 3.14159)', 'The orientation the character is facing. (North = 0.0, South = 3.14159)');
INSERT INTO `dbdocsfields` VALUES ('205', '0', 'characters', 'playerBytes', 'zzzz', 'zzzz');
INSERT INTO `dbdocsfields` VALUES ('206', '0', 'characters', 'playerBytes2', 'zzzz', 'zzzz');
INSERT INTO `dbdocsfields` VALUES ('207', '0', 'characters', 'playerFlags', 'zzzz', 'zzzz');
INSERT INTO `dbdocsfields` VALUES ('208', '0', 'characters', 'position_x', 'The x position of the character', 'The x position of the character');
INSERT INTO `dbdocsfields` VALUES ('209', '0', 'characters', 'position_y', 'The y position of the character', 'The y position of the character');
INSERT INTO `dbdocsfields` VALUES ('210', '0', 'characters', 'position_z', 'The z position of the character', 'The z position of the character');
INSERT INTO `dbdocsfields` VALUES ('211', '0', 'characters', 'power1', 'zzzz', 'zzzz');
INSERT INTO `dbdocsfields` VALUES ('212', '0', 'characters', 'power2', 'zzzz', 'zzzz');
INSERT INTO `dbdocsfields` VALUES ('213', '0', 'characters', 'power3', 'zzzz', 'zzzz');
INSERT INTO `dbdocsfields` VALUES ('214', '0', 'characters', 'power4', 'zzzz', 'zzzz');
INSERT INTO `dbdocsfields` VALUES ('215', '0', 'characters', 'power5', 'zzzz', 'zzzz');
INSERT INTO `dbdocsfields` VALUES ('216', '0', 'characters', 'race', 'The race of the character.', 'The race of the character.\r\n\r\n');
INSERT INTO `dbdocsfields` VALUES ('217', '0', 'characters', 'resettalents_cost', 'The cost for the character to reset its talents, measured in copper.', 'The cost for the character to reset its talents, measured in copper.');
INSERT INTO `dbdocsfields` VALUES ('218', '0', 'characters', 'resettalents_time', 'zzzz', 'zzzz');
INSERT INTO `dbdocsfields` VALUES ('219', '0', 'characters', 'rest_bonus', 'zzzz', 'zzzz');
INSERT INTO `dbdocsfields` VALUES ('220', '0', 'characters', 'stable_slots', 'The number of stable slots the player has available. Maximum is 2.', 'The number of stable slots the player has available. Maximum is 2.');
INSERT INTO `dbdocsfields` VALUES ('221', '0', 'characters', 'stored_dishonorable_kills', 'zzzz', 'zzzz');
INSERT INTO `dbdocsfields` VALUES ('222', '0', 'characters', 'stored_honor_rating', 'zzzz', 'zzzz');
INSERT INTO `dbdocsfields` VALUES ('223', '0', 'characters', 'stored_honorable_kills', 'zzzz', 'zzzz');
INSERT INTO `dbdocsfields` VALUES ('224', '0', 'characters', 'taxi_path', 'Stores the players current taxi path (TaxiPath.dbc) if logged off while on one.', 'Stores the players current taxi path (TaxiPath.dbc) if logged off while on one.');
INSERT INTO `dbdocsfields` VALUES ('225', '0', 'characters', 'taximask', 'zzzz', 'zzzz');
INSERT INTO `dbdocsfields` VALUES ('226', '0', 'characters', 'totaltime', 'The total time that the character has been active in the world.', 'The total time that the character has been active in the world, measured in seconds.');
INSERT INTO `dbdocsfields` VALUES ('227', '0', 'characters', 'trans_o', 'zzzz', 'zzzz');
INSERT INTO `dbdocsfields` VALUES ('228', '0', 'characters', 'trans_x', 'zzzz', 'zzzz');
INSERT INTO `dbdocsfields` VALUES ('229', '0', 'characters', 'trans_y', 'zzzz', 'zzzz');
INSERT INTO `dbdocsfields` VALUES ('230', '0', 'characters', 'trans_z', 'zzzz', 'zzzz');
INSERT INTO `dbdocsfields` VALUES ('231', '0', 'characters', 'transguid', 'zzzz', 'zzzz');
INSERT INTO `dbdocsfields` VALUES ('232', '0', 'characters', 'watchedFaction', 'zzzz', 'zzzz');
INSERT INTO `dbdocsfields` VALUES ('233', '0', 'characters', 'xp', 'The total amount of xp that the signified player has.', 'The total amount of xp that the signified player has.');
INSERT INTO `dbdocsfields` VALUES ('234', '0', 'characters', 'zone', 'The zone ID the character is in.', 'The zone ID the character is in.');
INSERT INTO `dbdocsfields` VALUES ('235', '0', 'corpse', 'corpse_type', 'The Display Type of the corpse.', 'The Display Type of the corpse:\r\n<br />\r\n');
INSERT INTO `dbdocsfields` VALUES ('236', '0', 'corpse', 'guid', 'The character global unique identifier of the corpse.', 'The character global unique identifier of the corpse.');
INSERT INTO `dbdocsfields` VALUES ('237', '0', 'corpse', 'instance', 'The instance ID that the corpse is in.', 'The instance ID that the corpse is in.');
INSERT INTO `dbdocsfields` VALUES ('238', '0', 'corpse', 'map', 'The map ID the corpse is in. (See maps.dbc)', 'The map ID the corpse is in. (See maps.dbc)');
INSERT INTO `dbdocsfields` VALUES ('239', '0', 'corpse', 'orientation', 'The orientation of the corpse. (North = 0.0, South = 3.14159)', 'The orientation of the corpse. (North = 0.0, South = 3.14159)');
INSERT INTO `dbdocsfields` VALUES ('240', '0', 'corpse', 'player', 'The character global unique identifier. (See characters.guid).', 'The character global unique identifier. (See characters.guid).');
INSERT INTO `dbdocsfields` VALUES ('241', '0', 'corpse', 'position_x', 'The x position of the character', 'The x position of the character');
INSERT INTO `dbdocsfields` VALUES ('242', '0', 'corpse', 'position_y', 'The y position of the character', 'The y position of the character');
INSERT INTO `dbdocsfields` VALUES ('243', '0', 'corpse', 'position_z', 'The z position of the character', 'The z position of the character');
INSERT INTO `dbdocsfields` VALUES ('244', '0', 'corpse', 'time', 'zzzz', 'zzzz');
INSERT INTO `dbdocsfields` VALUES ('245', '0', 'creature_respawn', 'guid', 'zzzz', 'zzzz');
INSERT INTO `dbdocsfields` VALUES ('246', '0', 'creature_respawn', 'instance', 'zzzz', 'zzzz');
INSERT INTO `dbdocsfields` VALUES ('247', '0', 'creature_respawn', 'respawntime', 'zzzz', 'zzzz');
INSERT INTO `dbdocsfields` VALUES ('248', '0', 'dbdocsfields', 'fieldComment', 'zzzz', 'zzzz');
INSERT INTO `dbdocsfields` VALUES ('249', '0', 'dbdocsfields', 'fieldName', 'The fieldname in the table to link the note to.', 'The fieldname in the table to link the note to.');
INSERT INTO `dbdocsfields` VALUES ('250', '0', 'dbdocsfields', 'fieldNotes', 'The Field Note text', 'The Field Note text');
INSERT INTO `dbdocsfields` VALUES ('251', '0', 'dbdocsfields', 'tableName', 'The table name to link the note to.', 'The table name to link the note to.');
INSERT INTO `dbdocsfields` VALUES ('252', '0', 'dbdocssubtables', 'subTableContent', 'The Content of the subTable', 'The Content of the subTable.');
INSERT INTO `dbdocsfields` VALUES ('253', '0', 'dbdocssubtables', 'subTableId', 'The Lookup Id of the subTable', 'This is the Lookup Id of the subTable');
INSERT INTO `dbdocsfields` VALUES ('254', '0', 'dbdocssubtables', 'subTableName', 'The Name of the SubTable', 'The Name of the SubTable');
INSERT INTO `dbdocsfields` VALUES ('255', '0', 'dbdocssubtables', 'subTableTemplate', 'The SubTable Template', 'The SubTable Template, Used to create the SubTableContent field content');
INSERT INTO `dbdocsfields` VALUES ('256', '0', 'dbdocstable', 'tableName', 'The table name to link the note to.', 'The table name to link the note to.');
INSERT INTO `dbdocsfields` VALUES ('257', '0', 'dbdocstable', 'tableNotes', 'The table note text.', 'The table note text.');
INSERT INTO `dbdocsfields` VALUES ('258', '0', 'game_event_status', 'event', 'The Event Id (see game_event.is) of currently active game events.', 'The Event Id (see game_event.is) of currently active game events.<br />\r\n\r\nOnce the event is complete, the entry is removed.');
INSERT INTO `dbdocsfields` VALUES ('259', '0', 'gameobject_respawn', 'guid', 'zzzz', 'zzzz');
INSERT INTO `dbdocsfields` VALUES ('260', '0', 'gameobject_respawn', 'instance', 'zzzz', 'zzzz');
INSERT INTO `dbdocsfields` VALUES ('261', '0', 'gameobject_respawn', 'respawntime', 'zzzz', 'zzzz');
INSERT INTO `dbdocsfields` VALUES ('262', '0', 'group_instance', 'instance', 'ID of the Instance session the group has enterd.', 'ID of the Instance session the group has enterd.');
INSERT INTO `dbdocsfields` VALUES ('263', '0', 'group_instance', 'leaderGuid', 'The Guid of the group leader. (See characters.guid)', 'The Guid of the group leader. (See characters.guid)');
INSERT INTO `dbdocsfields` VALUES ('264', '0', 'group_instance', 'permanent', 'Boolean flag if the group is bound to the Instance or not', 'Boolean flag if the group is bound to the Instance or not');
INSERT INTO `dbdocsfields` VALUES ('265', '0', 'group_member', 'assistant', 'zzzz', 'zzzz');
INSERT INTO `dbdocsfields` VALUES ('266', '0', 'group_member', 'groupId', 'zzzz', 'zzzz');
INSERT INTO `dbdocsfields` VALUES ('267', '0', 'group_member', 'memberGuid', 'zzzz', 'zzzz');
INSERT INTO `dbdocsfields` VALUES ('268', '0', 'group_member', 'subgroup', 'zzzz', 'zzzz');
INSERT INTO `dbdocsfields` VALUES ('269', '0', 'groups', 'groupId', 'zzzz', 'zzzz');
INSERT INTO `dbdocsfields` VALUES ('270', '0', 'groups', 'icon1', 'zzzz', 'zzzz');
INSERT INTO `dbdocsfields` VALUES ('271', '0', 'groups', 'icon2', 'zzzz', 'zzzz');
INSERT INTO `dbdocsfields` VALUES ('272', '0', 'groups', 'icon3', 'zzzz', 'zzzz');
INSERT INTO `dbdocsfields` VALUES ('273', '0', 'groups', 'icon4', 'zzzz', 'zzzz');
INSERT INTO `dbdocsfields` VALUES ('274', '0', 'groups', 'icon5', 'zzzz', 'zzzz');
INSERT INTO `dbdocsfields` VALUES ('275', '0', 'groups', 'icon6', 'zzzz', 'zzzz');
INSERT INTO `dbdocsfields` VALUES ('276', '0', 'groups', 'icon7', 'zzzz', 'zzzz');
INSERT INTO `dbdocsfields` VALUES ('277', '0', 'groups', 'icon8', 'zzzz', 'zzzz');
INSERT INTO `dbdocsfields` VALUES ('278', '0', 'groups', 'isRaid', 'zzzz', 'zzzz');
INSERT INTO `dbdocsfields` VALUES ('279', '0', 'groups', 'leaderGuid', 'zzzz', 'zzzz');
INSERT INTO `dbdocsfields` VALUES ('280', '0', 'groups', 'looterGuid', 'zzzz', 'zzzz');
INSERT INTO `dbdocsfields` VALUES ('281', '0', 'groups', 'lootMethod', 'zzzz', 'zzzz');
INSERT INTO `dbdocsfields` VALUES ('282', '0', 'groups', 'lootThreshold', 'zzzz', 'zzzz');
INSERT INTO `dbdocsfields` VALUES ('283', '0', 'groups', 'mainAssistant', 'zzzz', 'zzzz');
INSERT INTO `dbdocsfields` VALUES ('284', '0', 'groups', 'mainTank', 'zzzz', 'zzzz');
INSERT INTO `dbdocsfields` VALUES ('285', '0', 'guild', 'BackgroundColor', 'The background color of the guild tabard.', 'The background color of the guild tabard.');
INSERT INTO `dbdocsfields` VALUES ('286', '0', 'guild', 'BorderColor', 'The border color of the guild tabard.', 'The border color of the guild tabard.');
INSERT INTO `dbdocsfields` VALUES ('287', '0', 'guild', 'BorderStyle', 'The border style of the guild tabard.', 'The border style of the guild tabard.');
INSERT INTO `dbdocsfields` VALUES ('288', '0', 'guild', 'createdate', 'The date when the guild was created.', 'The date when the guild was created.');
INSERT INTO `dbdocsfields` VALUES ('289', '0', 'guild', 'EmblemColor', 'The emblem color of the guild tabard.', 'The emblem color of the guild tabard.');
INSERT INTO `dbdocsfields` VALUES ('290', '0', 'guild', 'EmblemStyle', 'The emblem style of the guild tabard.', 'The emblem style of the guild tabard.');
INSERT INTO `dbdocsfields` VALUES ('291', '0', 'guild', 'guildid', 'The ID of the guild.', 'The ID of the guild. This number is unique to each guild and is the main method to identify a guild.');
INSERT INTO `dbdocsfields` VALUES ('292', '0', 'guild', 'info', 'The text message that appears in the Guild Information box.', 'The text message that appears in the Guild Information box.');
INSERT INTO `dbdocsfields` VALUES ('293', '0', 'guild', 'leaderguid', 'The GUID of the character who created the guild. (See characters.guid)', 'The GUID of the character who created the guild. (See characters.guid)');
INSERT INTO `dbdocsfields` VALUES ('294', '0', 'guild', 'motd', 'The text that appears in the Message Of The Day box.', 'The text that appears in the Message Of The Day box.');
INSERT INTO `dbdocsfields` VALUES ('295', '0', 'guild', 'name', 'The guild name.', 'The guild name.');
INSERT INTO `dbdocsfields` VALUES ('296', '0', 'guild_eventlog', 'EventType', 'The Guild Event Type.', 'The Guild Event Type:\r\n\r\n');
INSERT INTO `dbdocsfields` VALUES ('297', '0', 'guild_eventlog', 'guildid', 'Id of related guild. (See guild.guildid).', 'Id of related guild. (See guild.guildid).');
INSERT INTO `dbdocsfields` VALUES ('298', '0', 'guild_eventlog', 'LogGuid', 'A unique identifier given to each log entry to distinguish it.', 'A unique identifier given to each log entry to distinguish one entry from another. Two guild event logs can NOT have same GUID.');
INSERT INTO `dbdocsfields` VALUES ('299', '0', 'guild_eventlog', 'NewRank', 'Id of new rank of PlayerGuid2. (See guild_rank.rid)', 'Id of new rank of PlayerGuid2. (See guild_rank.rid)');
INSERT INTO `dbdocsfields` VALUES ('300', '0', 'guild_eventlog', 'PlayerGuid1', 'Guid of character who made the change. (See character.guid)', 'Guid of character who made the change. (See character.guid)');
INSERT INTO `dbdocsfields` VALUES ('301', '0', 'guild_eventlog', 'PlayerGuid2', 'Guid of character who was \"changed\". (See character.guid)', 'Guid of character who was \"changed\". (See character.guid)');
INSERT INTO `dbdocsfields` VALUES ('302', '0', 'guild_eventlog', 'TimeStamp', 'Unix timestamp of when the event happened.', 'Unix timestamp of when the event happened.');
INSERT INTO `dbdocsfields` VALUES ('303', '0', 'guild_member', 'guid', 'The GUID of the player. (See character.guid)', 'The GUID of the player. (See character.guid)');
INSERT INTO `dbdocsfields` VALUES ('304', '0', 'guild_member', 'guildid', 'The ID of the guild that the member is a part of. (See guild.guildid)', 'The ID of the guild that the member is a part of. (See guild.guildid)');
INSERT INTO `dbdocsfields` VALUES ('305', '0', 'guild_member', 'offnote', 'The Officers Note set by officers in the guild.', 'The Officers Note set by officers in the guild, which can only be read by other officers of the guild.');
INSERT INTO `dbdocsfields` VALUES ('306', '0', 'guild_member', 'pnote', 'The Player Note set by the player.', 'The Player Note set by the player, which can be read by everyone in the guild.');
INSERT INTO `dbdocsfields` VALUES ('307', '0', 'guild_member', 'rank', 'The rank that the player has in the guild. (See guild_rank.rid)', 'The rank that the player has in the guild. (See guild_rank.rid)');
INSERT INTO `dbdocsfields` VALUES ('308', '0', 'guild_rank', 'guildid', 'The guild ID that the rank is part of. (See guild.guildid)', 'The guild ID that the rank is part of. (See guild.guildid)');
INSERT INTO `dbdocsfields` VALUES ('309', '0', 'guild_rank', 'rid', 'The particular rank ID. This number must be unique to each rank in a guild.', 'The particular rank ID. This number must be unique to each rank in a guild.');
INSERT INTO `dbdocsfields` VALUES ('310', '0', 'guild_rank', 'rights', 'The rights a player with this rank has in the guild.', 'The rights a player with this rank has in the guild. \r\nThe calculation of multiple rights is a bit different in this case as the rights do not all have 2^n values. \r\nTo combine ranks, you must do the OR operation (&#124;) on the two flags.<br />\r\n\r\n');
INSERT INTO `dbdocsfields` VALUES ('311', '0', 'guild_rank', 'rname', 'The name of the rank that is displayed in-game.', 'The name of the rank that is displayed in-game.');
INSERT INTO `dbdocsfields` VALUES ('312', '0', 'instance', 'data', 'Specific data belonging to the individual instance.', 'Specific data belonging to the individual instance.');
INSERT INTO `dbdocsfields` VALUES ('313', '0', 'instance', 'id', 'The instance ID. This number is unique to every instance.', 'The instance ID. This number is unique to every instance.');
INSERT INTO `dbdocsfields` VALUES ('314', '0', 'instance', 'map', 'The map ID the instance is in. (See Map.dbc)', 'The map ID the instance is in. (See Map.dbc)');
INSERT INTO `dbdocsfields` VALUES ('315', '0', 'instance', 'resettime', 'The time when the instance will be reset, in Unix time.', 'The time when the instance will be reset, in Unix time. This field is zero for raid and heroic instances.');
INSERT INTO `dbdocsfields` VALUES ('316', '0', 'instance_reset', 'mapid', 'The map ID of the instance. (See Map.dbc)', 'The map ID of the instance. (See Map.dbc)');
INSERT INTO `dbdocsfields` VALUES ('317', '0', 'instance_reset', 'resettime', 'Dungeon reset time in seconds.', 'Dungeon reset time in seconds.');
INSERT INTO `dbdocsfields` VALUES ('318', '0', 'item_instance', 'data', 'Much like the playerbytes fields in the characters table.', 'Much like the playerbytes fields in the characters table, this field has many number fields all separated by a space which contain specific individual item information like any enchantments applied to the item, etc.\r\n\r\n');
INSERT INTO `dbdocsfields` VALUES ('319', '0', 'item_instance', 'guid', 'The GUID of the item. This number is unique for each item instance.', 'The GUID of the item. This number is unique for each item instance.');
INSERT INTO `dbdocsfields` VALUES ('320', '0', 'item_instance', 'owner_guid', 'The GUID of the character who has ownership of this item. (See character.guid)', 'The GUID of the character who has ownership of this item. (See character.guid)');
INSERT INTO `dbdocsfields` VALUES ('321', '0', 'item_loot', 'amount', 'zzzz', 'zzzz');
INSERT INTO `dbdocsfields` VALUES ('322', '0', 'item_loot', 'guid', 'zzzz', 'zzzz');
INSERT INTO `dbdocsfields` VALUES ('323', '0', 'item_loot', 'itemid', 'zzzz', 'zzzz');
INSERT INTO `dbdocsfields` VALUES ('324', '0', 'item_loot', 'owner_guid', 'The GUID of the owner. (See character.guid)', 'The GUID of the owner. (See character.guid)');
INSERT INTO `dbdocsfields` VALUES ('325', '0', 'item_loot', 'property', 'zzzz', 'zzzz');
INSERT INTO `dbdocsfields` VALUES ('326', '0', 'item_text', 'id', 'The text entry ID. This number is unique to every text entry in this table.', 'The text entry ID. This number is unique to every text entry in this table.');
INSERT INTO `dbdocsfields` VALUES ('327', '0', 'item_text', 'text', 'The actual text that was sent as mail using the mail system.', 'The actual text that was sent as mail using the mail system. There are some special messages that are sent through the mail and therefore use this table but have a special format to them:\r\n\r\n<pre>Auction won (sent to bidder): \"&lt;owner\'s GUID as hex&gt;:&lt;winning bid in copper&gt;:&lt;buyout price in copper&gt;\"\r\n\r\nAuction successful (sent to owner): \"&lt;bidder\'s GUID as hex&gt;:&lt;winning bid in copper&gt;:0: &lt;deposit in copper&gt;:&lt;auction cut in copper&gt;\"</pre>\r\n');
INSERT INTO `dbdocsfields` VALUES ('328', '0', 'mail', 'checked', 'checked_flag\r\n.', 'checked_flag\r\n\r\nFlag Mask:<br />\r\n\r\n');
INSERT INTO `dbdocsfields` VALUES ('329', '0', 'mail', 'cod', 'Amount of money needed (COD).', 'Amount of money needed (COD).');
INSERT INTO `dbdocsfields` VALUES ('330', '0', 'mail', 'deliver_time', 'Current Unix Time + Unix Time till delivery.', 'Current Unix Time + Unix Time till delivery.<br />\r\nExample:<br />\r\ncurrent unix time + 86400 (seconds for one day) = delivery date<br />\r\nIn this example the mail would be delivered after one day.');
INSERT INTO `dbdocsfields` VALUES ('331', '0', 'mail', 'expire_time', 'Current Unix Time + Unix Time till expiry.', 'Current Unix Time + Unix Time till expiry.<br />\r\nExample:<br />\r\ncurrent unix time + 86400 (seconds for one day) = expiry date<br />\r\nIn this example the mail would expire after one day.');
INSERT INTO `dbdocsfields` VALUES ('332', '0', 'mail', 'has_items', 'zzzz', 'zzzz');
INSERT INTO `dbdocsfields` VALUES ('333', '0', 'mail', 'id', 'Unique message id. Every new message gets a new auto incremented id.', 'Unique message id. Every new message gets a new auto incremented id.');
INSERT INTO `dbdocsfields` VALUES ('334', '0', 'mail', 'itemTextId', 'zzzz', 'zzzz');
INSERT INTO `dbdocsfields` VALUES ('335', '0', 'mail', 'mailTemplateId', 'The Mail Template Id (See MailTemplate.dbc)', 'The Mail Template Id (See MailTemplate.dbc)');
INSERT INTO `dbdocsfields` VALUES ('336', '0', 'mail', 'messageType', 'message_type.', 'The type of the Message:</br >\r\n\r\n');
INSERT INTO `dbdocsfields` VALUES ('337', '0', 'mail', 'money', 'Amount of money sent.', 'Amount of money sent.<br />\r\nIf you want to send 100 gold 55 silver 33 copper then its 1005533');
INSERT INTO `dbdocsfields` VALUES ('338', '0', 'mail', 'receiver', 'Guid of the character who receives the mail.', 'Guid of the character who receives the mail.');
INSERT INTO `dbdocsfields` VALUES ('339', '0', 'mail', 'sender', 'Guid of the character who sends the mail.', 'Guid of the character who sends the mail.');
INSERT INTO `dbdocsfields` VALUES ('340', '0', 'mail', 'stationery', 'The StationeryID (See Stationery.dbc).', 'The StationeryID (See Stationery.dbc).<br />\r\n\r\n');
INSERT INTO `dbdocsfields` VALUES ('341', '0', 'mail', 'subject', 'The Subject of the mail.', 'The Subject of the mail.');
INSERT INTO `dbdocsfields` VALUES ('342', '0', 'mail_items', 'item_guid', 'zzzz', 'zzzz');
INSERT INTO `dbdocsfields` VALUES ('343', '0', 'mail_items', 'item_template', 'zzzz', 'zzzz');
INSERT INTO `dbdocsfields` VALUES ('344', '0', 'mail_items', 'mail_id', 'The Mail Id (See mail.id).', 'The Mail Id (See mail.id).');
INSERT INTO `dbdocsfields` VALUES ('345', '0', 'mail_items', 'receiver', 'Guid of the character who receives the mail.', 'Guid of the character who receives the mail.');
INSERT INTO `dbdocsfields` VALUES ('346', '0', 'pet_aura', 'basepoints0', 'zzzz', 'zzzz');
INSERT INTO `dbdocsfields` VALUES ('347', '0', 'pet_aura', 'basepoints1', 'zzzz', 'zzzz');
INSERT INTO `dbdocsfields` VALUES ('348', '0', 'pet_aura', 'basepoints2', 'zzzz', 'zzzz');
INSERT INTO `dbdocsfields` VALUES ('349', '0', 'pet_aura', 'caster_guid', 'The GUID of the player or creature who casted the aura. (See character.guid)', 'The GUID of the player or creature who casted the aura. (See character.guid)');
INSERT INTO `dbdocsfields` VALUES ('350', '0', 'pet_aura', 'effIndexMask', 'The effect index of the spell from which the aura came from.', 'The effect index of the spell from which the aura came from. A spell has up to three effects, with the index being 0, 1, or 2.');
INSERT INTO `dbdocsfields` VALUES ('351', '0', 'pet_aura', 'guid', 'The GUID of the target affected by the aura. (See character.guid)', 'The GUID of the target affected by the aura. (See character.guid)');
INSERT INTO `dbdocsfields` VALUES ('352', '0', 'pet_aura', 'item_guid', 'zzzz', 'zzzz');
INSERT INTO `dbdocsfields` VALUES ('353', '0', 'pet_aura', 'maxduration', 'The maximum duration of the aura.', 'The maximum duration of the aura.');
INSERT INTO `dbdocsfields` VALUES ('354', '0', 'pet_aura', 'periodictime0', 'zzzz', 'zzzz');
INSERT INTO `dbdocsfields` VALUES ('355', '0', 'pet_aura', 'periodictime1', 'zzzz', 'zzzz');
INSERT INTO `dbdocsfields` VALUES ('356', '0', 'pet_aura', 'periodictime2', 'zzzz', 'zzzz');
INSERT INTO `dbdocsfields` VALUES ('357', '0', 'pet_aura', 'remaincharges', 'The number of charges remaining on the aura.', 'The number of charges remaining on the aura.');
INSERT INTO `dbdocsfields` VALUES ('358', '0', 'pet_aura', 'remaintime', 'The time remaining in seconds on the aura. -1 means that the aura is indefinite.', 'The time remaining in seconds on the aura. -1 means that the aura is indefinite.');
INSERT INTO `dbdocsfields` VALUES ('359', '0', 'pet_aura', 'spell', 'The spell from which the aura was applied. (See Spell.dbc column 1)', 'The spell from which the aura was applied. (See Spell.dbc column 1)');
INSERT INTO `dbdocsfields` VALUES ('360', '0', 'pet_aura', 'stackcount', 'zzzz', 'zzzz');
INSERT INTO `dbdocsfields` VALUES ('361', '0', 'pet_spell', 'active', 'Boolean 0 or 1 controlling if the spell is active or not.', 'Boolean 0 or 1 controlling if the spell is active or not.');
INSERT INTO `dbdocsfields` VALUES ('362', '0', 'pet_spell', 'guid', 'The pet GUID. (See character_pet.id).', 'The pet GUID. (See character_pet.id).');
INSERT INTO `dbdocsfields` VALUES ('363', '0', 'pet_spell', 'spell', 'The spell ID. See (Spell.dbc)', 'The spell ID. See (Spell.dbc)');
INSERT INTO `dbdocsfields` VALUES ('364', '0', 'pet_spell_cooldown', 'guid', 'The GUID of the pet. (See character_pet.id)', 'The GUID of the pet. (See character_pet.id)');
INSERT INTO `dbdocsfields` VALUES ('365', '0', 'pet_spell_cooldown', 'spell', 'The spell ID to which the cooldown applies.', 'The spell ID to which the cooldown applies.');
INSERT INTO `dbdocsfields` VALUES ('366', '0', 'pet_spell_cooldown', 'time', 'The time when the cooldown expires, in Unix time.', 'The time when the cooldown expires, in Unix time.');
INSERT INTO `dbdocsfields` VALUES ('367', '0', 'petition', 'name', 'The name of the guild or arena team that the player is trying to petition.', 'The name of the guild or arena team that the player is trying to ask for petitions for.');
INSERT INTO `dbdocsfields` VALUES ('368', '0', 'petition', 'ownerguid', 'The petition', 'The petition');
INSERT INTO `dbdocsfields` VALUES ('369', '0', 'petition', 'petitionguid', 'The GUID of the petition item. See (item_instance.guid)', 'The GUID of the petition item. See (item_instance.guid)');
INSERT INTO `dbdocsfields` VALUES ('370', '0', 'petition_sign', 'ownerguid', 'The GUID of the owner that is trying to make the guild/arena team.', 'The GUID of the owner that is trying to make the guild/arena team. (See characters.guid).');
INSERT INTO `dbdocsfields` VALUES ('371', '0', 'petition_sign', 'petitionguid', 'The GUID of the charter item. (See item_template.guid)', 'The GUID of the charter item. (See item_template.guid)');
INSERT INTO `dbdocsfields` VALUES ('372', '0', 'petition_sign', 'player_account', 'The account ID of the player that has signed the charter (See account.id).', 'The account ID of the player that has signed the charter (See account.id). No two players can sign the same charter from the same account.');
INSERT INTO `dbdocsfields` VALUES ('373', '0', 'petition_sign', 'playerguid', 'The GUID of the player that has signed the charter. (See character.guid)', 'The GUID of the player that has signed the charter. (See character.guid)');
INSERT INTO `dbdocsfields` VALUES ('374', '0', 'saved_variables', 'cleaning_flags', 'The flags controlling character cleanup.', 'The flags controlling character cleanup:<br />\r\n\r\n');
INSERT INTO `dbdocsfields` VALUES ('375', '0', 'saved_variables', 'NextMaintenanceDate', 'The Date when the Honor Points / Rank etc. are updated.', 'The Date when the Honor Points / Rank etc. are updated.<br />\r\n\r\nThe date is then set 7 days in the future.');
INSERT INTO `dbdocsfields` VALUES ('376', '0', 'world', 'data', 'Specific data belonging to the world.', 'Specific data belonging to the world.');
INSERT INTO `dbdocsfields` VALUES ('377', '0', 'world', 'map', 'The map ID (See Map.dbc)', 'The map ID (See Map.dbc)');
