/*
Navicat MySQL Data Transfer

Source Server         : Lokak (xampp)
Source Server Version : 50505
Source Host           : localhost:3306
Source Database       : mangos

Target Server Type    : MYSQL
Target Server Version : 50505
File Encoding         : 65001

Date: 2019-05-30 01:34:34
*/

SET FOREIGN_KEY_CHECKS=0;
-- ----------------------------
-- Table structure for `creature_ai_texts`
-- ----------------------------
DROP TABLE IF EXISTS `creature_ai_texts`;
CREATE TABLE `creature_ai_texts` (
  `entry` mediumint(8) NOT NULL,
  `content_default` text NOT NULL,
  `content_loc1` text,
  `content_loc2` text,
  `content_loc3` text,
  `content_loc4` text,
  `content_loc5` text,
  `content_loc6` text,
  `content_loc7` text,
  `content_loc8` text,
  `sound` mediumint(8) unsigned NOT NULL DEFAULT '0',
  `type` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `language` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `emote` smallint(5) unsigned NOT NULL DEFAULT '0',
  `comment` text,
  PRIMARY KEY (`entry`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 ROW_FORMAT=FIXED COMMENT='Script Texts';

-- ----------------------------
-- Records of creature_ai_texts
-- ----------------------------
INSERT INTO `creature_ai_texts` VALUES ('-1422', 'There you have it. Our lesson on summoning has come to an end. A new class will begin shortly, so if you wish to brush up, feel free to stay around.', null, null, null, null, null, null, null, null, '0', '0', '33', '0', '5702');
INSERT INTO `creature_ai_texts` VALUES ('-1421', 'I doubt you have had much occasion to see such a creature. These demonic equines will make your travels much faster by acting as your mount as long as you control them. However, they are difficult to control, so be sure you are ready before attempting it.', null, null, null, null, null, null, null, null, '0', '0', '33', '0', '5702');
INSERT INTO `creature_ai_texts` VALUES ('-1420', 'When facing a spellcaster of any kind, this feral beast will be your best friend. Now, let us take a look at something a bit different. This next creature will aid your travels and make your future journeys much easier. Let\'s take a look at a felsteed.', null, null, null, null, null, null, null, null, '0', '0', '33', '0', '5702');
INSERT INTO `creature_ai_texts` VALUES ('-1419', 'What you see before you is a felhunter. This creature\'s natural talents include spell lock and other abilities which make it unequalled when facing a magically attuned opponent.', null, null, null, null, null, null, null, null, '0', '0', '33', '0', '5702');
INSERT INTO `creature_ai_texts` VALUES ('-1418', 'Study hard and you might one day be able to summon one on your own, but for now it\'s time to move on to the felhunter.', null, null, null, null, null, null, null, null, '0', '0', '33', '0', '5702');
INSERT INTO `creature_ai_texts` VALUES ('-1417', 'All right now. Aside from the obvious distractions a minion like this will provide against your more masculine foes, she is also capable of dealing out impressive amounts of damage. However, her fragile endurance makes her almost useless as a shield.', null, null, null, null, null, null, null, null, '0', '0', '33', '0', '5702');
INSERT INTO `creature_ai_texts` VALUES ('-1416', 'If you\'ve never seen one, it is a sight to behold. A very impressive creature both on and off the field of battle. Next, let us take a look at what I am sure all you male students have been waiting for. The succubus.', null, null, null, null, null, null, null, null, '0', '0', '33', '0', '5702');
INSERT INTO `creature_ai_texts` VALUES ('-1415', 'This demonic entity is known as the Voidwalker. Its strength and endurance are significant, making it ideal for defense. Send it to attack your enemy, then use it as a shield while you use your spells and abilities to drain away your opponent\'s life.', null, null, null, null, null, null, null, null, '0', '0', '33', '0', '5702');
INSERT INTO `creature_ai_texts` VALUES ('-1414', 'Now that you have had a chance to study imp, let us move on the next minion you will be able to summon, the voidwalker.', null, null, null, null, null, null, null, null, '0', '0', '33', '0', '5702');
INSERT INTO `creature_ai_texts` VALUES ('-1413', 'This foul little beast is the imp. It is small and weak, making it almost useless as a meatshield, and its damage output is mediocre at best. This creature is best used for support of a larger group.', null, null, null, null, null, null, null, null, '0', '0', '33', '0', '5702');
INSERT INTO `creature_ai_texts` VALUES ('-1412', 'The easiest creature for you to summon is the imp. You should already be able to bring forth this minion but for completeness\' sake I will start with him.', null, null, null, null, null, null, null, null, '0', '0', '33', '0', '5702');
INSERT INTO `creature_ai_texts` VALUES ('-1411', 'If you\'re here, then it means you are prepared to begin the study of summoning demonic cohorts to do your bidding. We will start with the lowliest creatures you will be able to call and continue from there. Let us begin.', null, null, null, null, null, null, null, null, '0', '0', '33', '0', '5702');
INSERT INTO `creature_ai_texts` VALUES ('-1320', '%s splits into two new Lava Spawns!', null, null, null, null, null, null, null, null, '0', '2', '0', '0', 'Lava Spawn - Split Emote');
INSERT INTO `creature_ai_texts` VALUES ('-1319', 'Silithid Creeper Egg splits open!', null, null, null, null, null, null, null, null, '0', '2', '0', '0', '5781');
INSERT INTO `creature_ai_texts` VALUES ('-1318', 'Silithid Creeper Egg begins to crack and open...', null, null, null, null, null, null, null, null, '0', '2', '0', '0', '5781');
INSERT INTO `creature_ai_texts` VALUES ('-1317', 'Silithid Creeper lays an egg!', null, null, null, null, null, null, null, null, '0', '2', '0', '0', '3250');
INSERT INTO `creature_ai_texts` VALUES ('-1316', 'Don\'t worry, I\'ll find a good home for ya.', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '8666');
INSERT INTO `creature_ai_texts` VALUES ('-1315', 'Will someone please give my little kitten a good home?', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '8666');
INSERT INTO `creature_ai_texts` VALUES ('-1314', 'What does allergic mean anyway? And what does it have to do with either of my kitties?', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '8666');
INSERT INTO `creature_ai_texts` VALUES ('-1313', 'Can anyone give my adorable, extra little kitty a home?', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '8666');
INSERT INTO `creature_ai_texts` VALUES ('-1312', 'I can\'t believe dad won\'t let me keep your sister.', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '8666');
INSERT INTO `creature_ai_texts` VALUES ('-1310', 'Welcome to flavor country!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '11058');
INSERT INTO `creature_ai_texts` VALUES ('-1308', 'The Scarlet Crusade shall smite the wicked and drive evil from these lands!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'Scarlet Monastery');
INSERT INTO `creature_ai_texts` VALUES ('-1307', 'There is no escape for you.  The Crusade shall destroy all who carry the scourge\'s taint.', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'Scarlet Monastery');
INSERT INTO `creature_ai_texts` VALUES ('-1306', 'You carry the taint of the scourge.  Prepare to enter the twisting nether.', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'Scarlet Monastery');
INSERT INTO `creature_ai_texts` VALUES ('-1305', 'The light condemns all who harbor evil.  Now you will die!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'Scarlet Monastery');
INSERT INTO `creature_ai_texts` VALUES ('-1302', 'Death take me! I cannot go on! I have nothing left...', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '14484, 14485');
INSERT INTO `creature_ai_texts` VALUES ('-1301', 'I won\'t make it... go... go on without me...', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '14484, 14485');
INSERT INTO `creature_ai_texts` VALUES ('-1300', 'Should I live through this, I shall make it my life\'s sole ambition to destroy Arthas...', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '14484, 14485');
INSERT INTO `creature_ai_texts` VALUES ('-1299', 'Stranger, find the fallen Prince Menethil and end his reign of terror.', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '14484, 14485');
INSERT INTO `creature_ai_texts` VALUES ('-1298', 'At last, it ends...', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '14484, 14485');
INSERT INTO `creature_ai_texts` VALUES ('-1297', 'We shall be reunited once more, my love...', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '14484, 14485');
INSERT INTO `creature_ai_texts` VALUES ('-1296', 'The power of the light is truly great and merciful.', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '14484, 14485');
INSERT INTO `creature_ai_texts` VALUES ('-1295', 'Foolish mortal, you serve me now!', null, null, null, null, null, null, null, null, '8273', '1', '0', '0', '12557');
INSERT INTO `creature_ai_texts` VALUES ('-1294', 'Intruders have breached the hatchery! Sound the alarm! Protect the eggs at all costs!', null, null, null, null, null, null, null, null, '8272', '1', '0', '0', '12557');
INSERT INTO `creature_ai_texts` VALUES ('-1226', 'Oh now you\'ve gone and angered me! Time to see the true force of the Stone of Tides!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '2624');
INSERT INTO `creature_ai_texts` VALUES ('-1225', 'Too...easy!', null, null, null, null, null, null, null, null, '5826', '1', '0', '0', '7358');
INSERT INTO `creature_ai_texts` VALUES ('-1224', 'I am the hand of the Lich King!', null, null, null, null, null, null, null, null, '5827', '1', '0', '0', '7358');
INSERT INTO `creature_ai_texts` VALUES ('-1223', 'Come, spirits, attend your master!', null, null, null, null, null, null, null, null, '5829', '1', '0', '0', '7358');
INSERT INTO `creature_ai_texts` VALUES ('-1222', 'To me, my servants!', null, null, null, null, null, null, null, null, '5828', '1', '0', '0', '7358');
INSERT INTO `creature_ai_texts` VALUES ('-1221', 'You\'ll never leave this place... alive.', null, null, null, null, null, null, null, null, '5825', '1', '0', '0', '7358');
INSERT INTO `creature_ai_texts` VALUES ('-1213', 'I HAVE YOUR LITTLE BELT TIED AROUND MY FINGER, SMOTTS. DON\'T YOU WANT IT BACK?', null, null, null, null, null, null, null, null, '0', '1', '0', '0', 'Mok\'Rash - Random Yell');
INSERT INTO `creature_ai_texts` VALUES ('-1212', 'YOU WERE SUCH GOOD SPORT THE LAST TIME...COME OUT!', null, null, null, null, null, null, null, null, '0', '1', '0', '0', 'Mok\'Rash - Random Yell');
INSERT INTO `creature_ai_texts` VALUES ('-1211', 'HAVE YOU RUN OUT OF SHIPS TO SEND? WHERE IS YOUR COURAGE?', null, null, null, null, null, null, null, null, '0', '1', '0', '0', 'Mok\'Rash - Random Yell');
INSERT INTO `creature_ai_texts` VALUES ('-1210', 'I PROMISE I WON\'T KILL YOUR CREW THIS TIME. HAH! BUT MY BROTHER MIGHT EAT THEM!', null, null, null, null, null, null, null, null, '0', '1', '0', '0', 'Mok\'Rash - Random Yell');
INSERT INTO `creature_ai_texts` VALUES ('-1209', 'COME OUT TO JANEIRO\'S POINT. I\'M WAITING FOR YOU, SMOTTS...', null, null, null, null, null, null, null, null, '0', '1', '0', '0', 'Mok\'Rash - Random Yell');
INSERT INTO `creature_ai_texts` VALUES ('-1208', 'DON\'T LET THIS STATUE BE MY ONLY COMPANY, COME OUT AND PLAY!', null, null, null, null, null, null, null, null, '0', '1', '0', '0', 'Mok\'Rash - Random Yell');
INSERT INTO `creature_ai_texts` VALUES ('-1207', 'SMOTTS! HEY, SMOTTS! COME OUT AND PLAY!', null, null, null, null, null, null, null, null, '0', '1', '0', '0', 'Mok\'Rash - Random Yell');
INSERT INTO `creature_ai_texts` VALUES ('-1206', 'SMOTTS, I HAVE YOUR LITTLE BELT....COME GET IT!', null, null, null, null, null, null, null, null, '0', '1', '0', '0', 'Mok\'Rash - Random Yell');
INSERT INTO `creature_ai_texts` VALUES ('-1205', 'Release the hounds!', null, null, null, null, null, null, null, null, '5841', '1', '0', '0', '3974');
INSERT INTO `creature_ai_texts` VALUES ('-1204', 'More... More souls.', null, null, null, null, null, null, null, null, '5845', '1', '0', '0', '4543');
INSERT INTO `creature_ai_texts` VALUES ('-1203', 'No rest, for the angry dead.', null, null, null, null, null, null, null, null, '5846', '1', '0', '0', '4543');
INSERT INTO `creature_ai_texts` VALUES ('-1202', 'We hunger for vengeance.', null, null, null, null, null, null, null, null, '5844', '1', '0', '0', '4543');
INSERT INTO `creature_ai_texts` VALUES ('-1201', 'Purged by pain!', null, null, null, null, null, null, null, null, '5848', '1', '0', '0', '3983');
INSERT INTO `creature_ai_texts` VALUES ('-1200', 'I\'ll rip the secrets from your flesh!', null, null, null, null, null, null, null, null, '5850', '1', '0', '0', '3983');
INSERT INTO `creature_ai_texts` VALUES ('-1199', 'Naughty secrets!', null, null, null, null, null, null, null, null, '5849', '1', '0', '0', '3983');
INSERT INTO `creature_ai_texts` VALUES ('-1198', 'Tell me... tell me everything!', null, null, null, null, null, null, null, null, '5847', '1', '0', '0', '3983');
INSERT INTO `creature_ai_texts` VALUES ('-1197', 'TIMMY!', null, null, null, null, null, null, null, null, '0', '1', '0', '0', '10808');
INSERT INTO `creature_ai_texts` VALUES ('-1196', 'You just got MALOWNED!', null, null, null, null, null, null, null, null, '0', '1', '0', '0', '11143');
INSERT INTO `creature_ai_texts` VALUES ('-1195', 'Prepare to be Malowned!', null, null, null, null, null, null, null, null, '0', '1', '0', '0', '11143');
INSERT INTO `creature_ai_texts` VALUES ('-1194', 'Emperor Thaurissan does not wish to be disturbed! Turn back now or face your doom, weak mortals!', null, null, null, null, null, null, null, null, '0', '1', '0', '0', '9938');
INSERT INTO `creature_ai_texts` VALUES ('-1161', 'Ooooooooh... $B To the plaguelands went old Duggan, ta\' send them Scourge back inta\' th\' groun\'. $B Where th\' scent of death is on th\' wind and everythin\' is mostly brown. $B An\' when he did arrive there, what\'d his dwarf eyes see? $B A hundred crates of barley there ta\' be makin\' inta\' mead! $B But tha\' mead was cursed with th\' plague o\' death, and now old Duggan, too. $B An\' surrounded by the Lich King\'s beasts, what could old Duggan do? $B But though I feel the plague within, my hopes \'ave not yet sunk. $B If\'n I\'m gonna be Scourge anyway, I might as well be drunk!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '10817');
INSERT INTO `creature_ai_texts` VALUES ('-1160', 'Ah ken see very well through this haze, but I\'d know tha\' smell anywhere! Die ye foul ogre!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '10817');
INSERT INTO `creature_ai_texts` VALUES ('-1159', 'Is that the best you can do?', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'High Overlord Saurfang - Say On Kill');
INSERT INTO `creature_ai_texts` VALUES ('-1158', 'As if we don\'t have enough problems, you go and create more!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'Argent Sentry, Argent Rider, Cenarion Hold Infantry - Random Say on Aggro');
INSERT INTO `creature_ai_texts` VALUES ('-1157', 'Please tell me that you didn\'t just do what I think you just did. Please tell me that I\'m not going to have to hurt you...', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'Argent Sentry, Argent Rider, Cenarion Hold Infantry - Random Say on Aggro');
INSERT INTO `creature_ai_texts` VALUES ('-1156', 'Taste blade, mongrel!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'Argent Sentry, Argent Rider, Cenarion Hold Infantry - Random Say on Aggro');
INSERT INTO `creature_ai_texts` VALUES ('-1155', 'For the Darkspear tribe!', null, null, null, null, null, null, null, null, '5881', '1', '0', '0', 'Vol\'jin- Random Yell and Sound on Aggro');
INSERT INTO `creature_ai_texts` VALUES ('-1154', 'Here come the voodoo!', null, null, null, null, null, null, null, null, '5881', '1', '0', '0', 'Vol\'jin - Random Yell and Sound on Aggro');
INSERT INTO `creature_ai_texts` VALUES ('-1153', 'You make big mistake, mon.', null, null, null, null, null, null, null, null, '5881', '1', '0', '0', 'Vol\'jin - Random Yell and Sound on Aggro');
INSERT INTO `creature_ai_texts` VALUES ('-1152', 'For Doomhammer!', null, null, null, null, null, null, null, null, '5880', '1', '0', '0', 'Thrall - Random Yell and Sound on Aggro');
INSERT INTO `creature_ai_texts` VALUES ('-1151', 'Lok\'Narosh!', null, null, null, null, null, null, null, null, '5880', '1', '0', '0', 'Thrall - Random Yell and Sound on Aggro');
INSERT INTO `creature_ai_texts` VALUES ('-1150', 'Your time has come!', null, null, null, null, null, null, null, null, '5880', '1', '0', '0', 'Thrall - Random Yell and Sound on Aggro');
INSERT INTO `creature_ai_texts` VALUES ('-1149', 'I hate resorting to violence!', null, null, null, null, null, null, null, null, '5882', '1', '0', '0', 'Lady Jaina Proudmoore - Random Yell and Sound on Aggro');
INSERT INTO `creature_ai_texts` VALUES ('-1148', 'You asked for it.', null, null, null, null, null, null, null, null, '5882', '1', '0', '0', 'Lady Jaina Proudmoore - Random Yell and Sound on Aggro');
INSERT INTO `creature_ai_texts` VALUES ('-1147', '%s \'s death cry has stirred the nearby silithid hive', null, null, null, null, null, null, null, null, '0', '0', '2', '0', '12178');
INSERT INTO `creature_ai_texts` VALUES ('-1146', 'Ach! Thank you so much I\'m free! Finally!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'Locheed text when spawned');
INSERT INTO `creature_ai_texts` VALUES ('-1145', 'Curse you! One day, vengeance will be mine!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'Private Merle Text');
INSERT INTO `creature_ai_texts` VALUES ('-1143', 'You will not harm Emperor Thaurissan!', null, null, null, null, null, null, null, null, '0', '1', '0', '0', '10076');
INSERT INTO `creature_ai_texts` VALUES ('-1142', 'I crush weaklings like you every day! Bring it on!', null, null, null, null, null, null, null, null, '0', '1', '0', '0', '16059');
INSERT INTO `creature_ai_texts` VALUES ('-1141', '%s squeezes the last bit of life out of $n and swallows their soul.', null, null, null, null, null, null, null, null, '0', '2', '0', '0', '15625');
INSERT INTO `creature_ai_texts` VALUES ('-1140', 'The Nightmare cannot be stopped!', null, null, null, null, null, null, null, null, '0', '1', '0', '0', '15625');
INSERT INTO `creature_ai_texts` VALUES ('-1139', 'Come, $n. See what the Nightmare brings...', null, null, null, null, null, null, null, null, '0', '1', '0', '0', '15625');
INSERT INTO `creature_ai_texts` VALUES ('-1138', 'Ahh, a new chew toy for my dogs!', null, null, null, null, null, null, null, null, '0', '1', '0', '0', 'Houndmaster Grebmar');
INSERT INTO `creature_ai_texts` VALUES ('-1137', 'WHO IS BOTHERING ME?', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'Arch Druid Fandral');
INSERT INTO `creature_ai_texts` VALUES ('-1136', 'Anudora!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '7999');
INSERT INTO `creature_ai_texts` VALUES ('-1135', 'None can stand against the serpent lords!', null, null, null, null, null, null, null, null, '5786', '1', '0', '0', '3671');
INSERT INTO `creature_ai_texts` VALUES ('-1134', 'Endudi Rifa!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '7999');
INSERT INTO `creature_ai_texts` VALUES ('-1133', 'For Kalimdor!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '7999');
INSERT INTO `creature_ai_texts` VALUES ('-1119', 'Kill $N!', null, null, null, null, null, null, null, null, '0', '1', '0', '25', '15392');
INSERT INTO `creature_ai_texts` VALUES ('-1058', '%s seems to no longer be able to cast spells...', null, null, null, null, null, null, null, null, '0', '2', '0', '0', '7666');
INSERT INTO `creature_ai_texts` VALUES ('-1057', 'Hey!  Get away from our treasure!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'Treasure Hunting Common Text');
INSERT INTO `creature_ai_texts` VALUES ('-1056', 'That\'s our treasure, you lubber!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'Treasure Hunting Common Text');
INSERT INTO `creature_ai_texts` VALUES ('-1055', 'No tampering with the mail!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '11142');
INSERT INTO `creature_ai_texts` VALUES ('-1054', '%s collapses but the broken body rises again!', null, null, null, null, null, null, null, null, '0', '2', '0', '0', '10381');
INSERT INTO `creature_ai_texts` VALUES ('-1048', 'You are in the presence of a god!', null, null, null, null, null, null, null, null, '0', '2', '0', '0', '15963');
INSERT INTO `creature_ai_texts` VALUES ('-1047', 'How dare you enter my sanctum!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '7271');
INSERT INTO `creature_ai_texts` VALUES ('-1045', 'More of the Warden\'s errand boys!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '1716');
INSERT INTO `creature_ai_texts` VALUES ('-1044', 'Fresh meat!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '1716');
INSERT INTO `creature_ai_texts` VALUES ('-1043', 'Death to the Warden\'s men!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '1716');
INSERT INTO `creature_ai_texts` VALUES ('-1042', 'I\'ll crush your skull beneath my boot!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '1716');
INSERT INTO `creature_ai_texts` VALUES ('-1041', 'Tell the Warden this prison is ours now!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '1716');
INSERT INTO `creature_ai_texts` VALUES ('-1040', 'Justice is done!', null, null, null, null, null, null, null, null, '5875', '1', '0', '0', '7274');
INSERT INTO `creature_ai_texts` VALUES ('-1039', 'Let the executions begin!', null, null, null, null, null, null, null, null, '5874', '1', '0', '0', '7274');
INSERT INTO `creature_ai_texts` VALUES ('-1038', 'Die, outlander!', null, null, null, null, null, null, null, null, '5877', '1', '0', '0', '7267');
INSERT INTO `creature_ai_texts` VALUES ('-1037', 'Feel the fury of the sands!', null, null, null, null, null, null, null, null, '5879', '1', '0', '0', '7267');
INSERT INTO `creature_ai_texts` VALUES ('-1036', 'The Sandfury reign supreme!', null, null, null, null, null, null, null, null, '5878', '1', '0', '0', '7267');
INSERT INTO `creature_ai_texts` VALUES ('-1035', 'This desert be mine!', null, null, null, null, null, null, null, null, '5876', '1', '0', '0', '7267');
INSERT INTO `creature_ai_texts` VALUES ('-1034', 'The Agamand Mills is held by the Scourge, $c. Join us!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '1657');
INSERT INTO `creature_ai_texts` VALUES ('-1033', 'Here to visit the family? Die, fool!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '1657');
INSERT INTO `creature_ai_texts` VALUES ('-1032', 'These lands shall be cleansed!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '1667');
INSERT INTO `creature_ai_texts` VALUES ('-1031', 'These undead atrocities will be destroyed!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '1667');
INSERT INTO `creature_ai_texts` VALUES ('-1030', 'The Scarlet Crusade shall not fail in it\'s mission!', null, null, null, null, null, null, null, null, '0', '0', '7', '0', '1667');
INSERT INTO `creature_ai_texts` VALUES ('-1029', 'You carry the taint of the scourge.  Prepare to enter the twisting nether.', null, null, null, null, null, null, null, null, '0', '0', '7', '0', 'Common Scarlet Text');
INSERT INTO `creature_ai_texts` VALUES ('-1028', 'The Scarlet Crusade shall smite the wicked and drive evil from these lands!', null, null, null, null, null, null, null, null, '0', '0', '7', '0', 'Common Scarlet Text');
INSERT INTO `creature_ai_texts` VALUES ('-1027', 'For a limited time only, Crunchy Frog available exclusively here at the Darkmoon Faire.', null, null, null, null, null, null, null, null, '0', '0', '0', '1', '14845');
INSERT INTO `creature_ai_texts` VALUES ('-1026', 'Darkmoon Dogs fresh off the grill. Come and get em while they\'re hot!', null, null, null, null, null, null, null, null, '0', '0', '0', '1', '14845');
INSERT INTO `creature_ai_texts` VALUES ('-1025', 'You\'ve got money and we\'ve got food. What are you waiting for?', null, null, null, null, null, null, null, null, '0', '0', '0', '1', '14845');
INSERT INTO `creature_ai_texts` VALUES ('-1024', 'Step right up! Get your Red Hot Wings right here!', null, null, null, null, null, null, null, null, '0', '0', '0', '1', '14845');
INSERT INTO `creature_ai_texts` VALUES ('-1023', 'And, don\'t forget to turn in your Darkmoon Faire Prize Tickets! All it takes is five or more and you\'re on your way to the most wondrous prizes on all of Azeroth. Everybody is a winner!', null, null, null, null, null, null, null, null, '0', '0', '0', '1', '14823');
INSERT INTO `creature_ai_texts` VALUES ('-1022', 'We have it all... delicious food, strong drink, exotic artifacts, fortunes read, amazing prizes and excitement without end!', null, null, null, null, null, null, null, null, '0', '0', '0', '1', '14823');
INSERT INTO `creature_ai_texts` VALUES ('-1021', 'Amaze at the wonders that the Darkmoon Faire has uncovered in this vast and mysterious world! We have spared no expense in bringing you excitement that children of all ages will delight in!', null, null, null, null, null, null, null, null, '0', '0', '0', '1', '14823');
INSERT INTO `creature_ai_texts` VALUES ('-1020', 'Step right up! Step right up! Greetings my friend. I\'m Silas Darkmoon and I want to welcome you to the greatest show on Azeroth! It\'s the Darkmoon Faire friend, and it\'s your lucky day! Sparing no expense, we\'ve gathered wonders and treats from around the world for your delight. Whether you\'re young or old, rich or poor, the Darkmoon Faire has it all!', null, null, null, null, null, null, null, null, '0', '0', '0', '1', '14823');
INSERT INTO `creature_ai_texts` VALUES ('-1019', 'This will teach you to lay off the herb, $r.', null, null, null, null, null, null, null, null, '0', '0', '0', '1', '11447');
INSERT INTO `creature_ai_texts` VALUES ('-990', 'Mommy!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'Common Text');
INSERT INTO `creature_ai_texts` VALUES ('-987', 'What? No you can\'t beat me! Me will return!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '14464');
INSERT INTO `creature_ai_texts` VALUES ('-986', 'You be too scared! Me find you!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '14464');
INSERT INTO `creature_ai_texts` VALUES ('-985', 'Mistress!! They seek to destroy your work!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '8581');
INSERT INTO `creature_ai_texts` VALUES ('-984', 'Who dares?! I will destroy you!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '8581');
INSERT INTO `creature_ai_texts` VALUES ('-983', 'You dare! Now feel my wrath!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '8578');
INSERT INTO `creature_ai_texts` VALUES ('-982', 'Is someone there? Tirion my old friend, is that you? Have you come to save us?', null, null, null, null, null, null, null, null, '0', '0', '0', '1', '11936');
INSERT INTO `creature_ai_texts` VALUES ('-981', 'Are They all.... Dead?', null, null, null, null, null, null, null, null, '0', '0', '0', '1', '11936');
INSERT INTO `creature_ai_texts` VALUES ('-974', 'Thieves! Scallywags! Rapscallions! Come face me gigantic pillas!', null, null, null, null, null, null, null, null, '0', '1', '0', '1', '14636');
INSERT INTO `creature_ai_texts` VALUES ('-935', 'Assassins... save... th... Magistraaa...', null, null, null, null, null, null, null, null, '0', '0', '0', '65', '2434');
INSERT INTO `creature_ai_texts` VALUES ('-934', '%s grabs the back of his neck and his eyes go wide.', null, null, null, null, null, null, null, null, '0', '2', '0', '0', '2434');
INSERT INTO `creature_ai_texts` VALUES ('-933', 'Guards to your posts! They must be after the Magistrate again. He must be protected! They could come from any direction!', null, null, null, null, null, null, null, null, '0', '0', '0', '1', '2434');
INSERT INTO `creature_ai_texts` VALUES ('-932', 'Help me! Help! Assassins in the hills! To arms! To arms!', null, null, null, null, null, null, null, null, '0', '1', '0', '22', '2434');
INSERT INTO `creature_ai_texts` VALUES ('-931', 'The undead shall feast on your soul, $N.', null, null, null, null, null, null, null, null, '0', '1', '0', '1', '2433');
INSERT INTO `creature_ai_texts` VALUES ('-930', 'Revenge shall be mine at last!', null, null, null, null, null, null, null, null, '0', '1', '0', '1', '2433');
INSERT INTO `creature_ai_texts` VALUES ('-929', 'I have risen!', null, null, null, null, null, null, null, null, '0', '1', '0', '1', '2433');
INSERT INTO `creature_ai_texts` VALUES ('-928', 'Southshore shall pay in blood!', null, null, null, null, null, null, null, null, '0', '1', '0', '1', '2433');
INSERT INTO `creature_ai_texts` VALUES ('-927', 'Intruders! Attack the intruders!', null, null, null, null, null, null, null, null, '0', '0', '33', '0', '2405');
INSERT INTO `creature_ai_texts` VALUES ('-926', 'I spent my whole life caring for these trees. Pruning and nurturing them... only fitting that they have joined me in death.', null, null, null, null, null, null, null, null, '0', '0', '1', '0', '2396');
INSERT INTO `creature_ai_texts` VALUES ('-925', 'This orchard is now as barren and lifeless as my rotting shell. Once these trees bloomed with fruit but now there is only rot.', null, null, null, null, null, null, null, null, '0', '0', '1', '0', '2396');
INSERT INTO `creature_ai_texts` VALUES ('-924', 'More agents of the Syndicate I\'ll wager! You\'ll never take back Alterac... Or Southshore!', null, null, null, null, null, null, null, null, '0', '0', '7', '0', '2276');
INSERT INTO `creature_ai_texts` VALUES ('-897', 'The light condemns all who harbor evil. Now you will die!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '1535');
INSERT INTO `creature_ai_texts` VALUES ('-896', 'You carry the taint of the scourge. Prepare to enter the twisting nether.', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '1535');
INSERT INTO `creature_ai_texts` VALUES ('-895', 'There is no escape for you. The Crusade shall destroy all who carry the scourge\'s taint.', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '1535');
INSERT INTO `creature_ai_texts` VALUES ('-829', '%s charges!', null, null, null, null, null, null, null, null, '0', '2', '0', '0', 'Common Emote');
INSERT INTO `creature_ai_texts` VALUES ('-828', '%s attacks Karang\'s Banner!', null, null, null, null, null, null, null, null, '0', '2', '0', '0', '12921');
INSERT INTO `creature_ai_texts` VALUES ('-827', 'No!  You cannot be stronger than the Foulweald!  No!!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '12918');
INSERT INTO `creature_ai_texts` VALUES ('-826', 'You are a little gnat to the Foulweald!  Die!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '12918');
INSERT INTO `creature_ai_texts` VALUES ('-825', 'This evil cannot be allowed to enter this world!  Come my children!', null, null, null, null, null, null, null, null, '0', '1', '0', '0', '5721');
INSERT INTO `creature_ai_texts` VALUES ('-824', 'Hakkar shall live again!', null, null, null, null, null, null, null, null, '5865', '1', '0', '0', '5721');
INSERT INTO `creature_ai_texts` VALUES ('-823', 'Join us!', null, null, null, null, null, null, null, null, '5864', '1', '0', '0', '5721');
INSERT INTO `creature_ai_texts` VALUES ('-822', 'The Soulflayer comes!', null, null, null, null, null, null, null, null, '5862', '1', '0', '0', '5721');
INSERT INTO `creature_ai_texts` VALUES ('-820', 'You know not what you do! We must destroy you for your own good.', null, null, null, null, null, null, null, null, '0', '1', '0', '0', '5721');
INSERT INTO `creature_ai_texts` VALUES ('-819', 'Turn back! Do not wake the dreamer!', null, null, null, null, null, null, null, null, '5866', '1', '0', '0', '5721');
INSERT INTO `creature_ai_texts` VALUES ('-817', 'So or\'manley fi siame Dim fus siame yudo', null, null, null, null, null, null, null, null, '5859', '1', '14', '0', '8580');
INSERT INTO `creature_ai_texts` VALUES ('-809', 'Help me crush these punys!', null, null, null, null, null, null, null, null, '0', '1', '0', '0', '14325');
INSERT INTO `creature_ai_texts` VALUES ('-808', 'No one get past me and threaten da king!  Ungh, take it!!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '14325');
INSERT INTO `creature_ai_texts` VALUES ('-807', '%s begins to retaliate all attacks against him!', null, null, null, null, null, null, null, null, '0', '2', '0', '0', '14325');
INSERT INTO `creature_ai_texts` VALUES ('-797', '%s puts his club away and begins swinging wildly!', null, null, null, null, null, null, null, null, '0', '2', '0', '0', '11441');
INSERT INTO `creature_ai_texts` VALUES ('-775', 'Alright! We Surrender... Just put your weapons down, I\'ll cooperate', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '5089');
INSERT INTO `creature_ai_texts` VALUES ('-770', 'I am summoned! Intruders, come to my tent and face your death!', null, null, null, null, null, null, null, null, '0', '1', '0', '0', '3395');
INSERT INTO `creature_ai_texts` VALUES ('-769', 'I am slain! Summon Verog!', null, null, null, null, null, null, null, null, '0', '1', '0', '0', 'Common Say for Kokar Centaurs');
INSERT INTO `creature_ai_texts` VALUES ('-764', 'Leave this place!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '10940');
INSERT INTO `creature_ai_texts` VALUES ('-716', 'Prepare yourselves for an eternity of anguish and torture - vengeance shall be mine...', null, null, null, null, null, null, null, null, '0', '1', '0', '0', '7664');
INSERT INTO `creature_ai_texts` VALUES ('-715', 'Face my champion, mortals!', null, null, null, null, null, null, null, null, '0', '1', '0', '0', '7664');
INSERT INTO `creature_ai_texts` VALUES ('-714', 'Let the flames of chaos engulf you!', null, null, null, null, null, null, null, null, '0', '1', '0', '0', '7664');
INSERT INTO `creature_ai_texts` VALUES ('-713', 'Ilifar, your master calls!', null, null, null, null, null, null, null, null, '0', '1', '0', '0', '7664');
INSERT INTO `creature_ai_texts` VALUES ('-712', 'The children of Sul will protect their master. Rise once more Sul\'lithuz!', null, null, null, null, null, null, null, null, '0', '1', '0', '0', '8127');
INSERT INTO `creature_ai_texts` VALUES ('-711', 'Rise and defend your master!', null, null, null, null, null, null, null, null, '0', '1', '0', '0', '8127');
INSERT INTO `creature_ai_texts` VALUES ('-710', 'Lunch has arrived, my beautiful children. Tear them to pieces!', null, null, null, null, null, null, null, null, '0', '1', '0', '0', '8127');
INSERT INTO `creature_ai_texts` VALUES ('-706', '%s weeps pitifully.', null, null, null, null, null, null, null, null, '0', '2', '0', '0', '10117');
INSERT INTO `creature_ai_texts` VALUES ('-705', '%s groans.', null, null, null, null, null, null, null, null, '0', '2', '0', '0', '10117');
INSERT INTO `creature_ai_texts` VALUES ('-704', '%s begs to be put out of his misery.', null, null, null, null, null, null, null, null, '0', '2', '0', '0', '10117');
INSERT INTO `creature_ai_texts` VALUES ('-703', 'You are not worth my time, $n.', null, null, null, null, null, null, null, null, '8614', '1', '0', '0', '15341');
INSERT INTO `creature_ai_texts` VALUES ('-702', 'Warriors! Captains! Continue the fight!', null, null, null, null, null, null, null, null, '8613', '1', '0', '0', '15341');
INSERT INTO `creature_ai_texts` VALUES ('-701', 'Impudent fools! I will kill you myself!', null, null, null, null, null, null, null, null, '8609', '1', '0', '0', '15341');
INSERT INTO `creature_ai_texts` VALUES ('-700', 'I have... failed.', null, null, null, null, null, null, null, null, '8594', '1', '0', '0', '15339');
INSERT INTO `creature_ai_texts` VALUES ('-699', 'You are terminated.', null, null, null, null, null, null, null, null, '8602', '1', '0', '0', '15339');
INSERT INTO `creature_ai_texts` VALUES ('-698', 'Sands of the desert, rise and block out the sun!', null, null, null, null, null, null, null, null, '8598', '1', '0', '0', '15339');
INSERT INTO `creature_ai_texts` VALUES ('-695', 'None may steal the secrets of the Makers!', null, null, null, null, null, null, null, null, '5851', '1', '0', '0', '7228');
INSERT INTO `creature_ai_texts` VALUES ('-694', '%s chips and splinters!', null, null, null, null, null, null, null, null, '0', '2', '0', '0', '7023');
INSERT INTO `creature_ai_texts` VALUES ('-667', 'Listen carefully, for the lord of Blackrock will surely destroy you, should you not be prepared.', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'Vaelan greetings');
INSERT INTO `creature_ai_texts` VALUES ('-666', 'At last: one among you is worthy of my knowledge. Worry not: I have probed your thoughts, no harm will come to you.', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'Vaelan greetings');
INSERT INTO `creature_ai_texts` VALUES ('-665', 'Obsidion, Rise and Serve your Master!', null, null, null, null, null, null, null, null, '0', '1', '0', '0', '8391');
INSERT INTO `creature_ai_texts` VALUES ('-664', 'Your task is complete. Prepare to meet your doom.', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '8391');
INSERT INTO `creature_ai_texts` VALUES ('-663', '%s\'s laughter trails off..', null, null, null, null, null, null, null, null, '0', '2', '0', '0', '8421');
INSERT INTO `creature_ai_texts` VALUES ('-662', 'And ultimately, it was Ragnaros that named me when I was reborn as an acolyte of fire: Lathoric... Lathoric the Black.', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '8421');
INSERT INTO `creature_ai_texts` VALUES ('-661', 'It was the will of Ragnaros that Obsidion be built. Obsidion will destroy the Blackrock orcs of Blackrock Spire, uniting us with our bretheren in the fiery depths.', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '8421');
INSERT INTO `creature_ai_texts` VALUES ('-660', 'When I stumbled upon the Suntara stones at the Grimesilt Digsite, the power of Ragnaros surged through my being. It was Ragnaros that gave me a purpose.', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '8421');
INSERT INTO `creature_ai_texts` VALUES ('-659', 'How easy it was to manipulate you into recovering the last Suntara stone from those imbeciles of the Twilight\'s Hammer..', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '8421');
INSERT INTO `creature_ai_texts` VALUES ('-658', 'Fools. I knew that if I played upon my brother\'s feeble emotions, he would send \'rescuers.\'', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '8421');
INSERT INTO `creature_ai_texts` VALUES ('-654', 'Snivvle is here! Snivvle claims the Coldtooth Mine!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '11677');
INSERT INTO `creature_ai_texts` VALUES ('-649', '%s goes into a drunken rage!', null, null, null, null, null, null, null, null, '0', '2', '0', '0', '14322');
INSERT INTO `creature_ai_texts` VALUES ('-648', '%s lets out a deep roar, alerting nearby allies and becoming enraged!', null, null, null, null, null, null, null, null, '0', '2', '0', '0', 'Dire Maul Guards');
INSERT INTO `creature_ai_texts` VALUES ('-587', 'Kibler is being investigated by G.E.T.A.', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '10262');
INSERT INTO `creature_ai_texts` VALUES ('-586', 'Opus wants some Cuergo\'s Gold... with worm.', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '10262');
INSERT INTO `creature_ai_texts` VALUES ('-585', 'They all go to the Spire but none never come back... just like Bijou.', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '10262');
INSERT INTO `creature_ai_texts` VALUES ('-584', 'Ask Kibler about the treasure! SQUAWK!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '10262');
INSERT INTO `creature_ai_texts` VALUES ('-583', 'SQUAWK!! *cough* *cough* I need to quit smoking!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '10262');
INSERT INTO `creature_ai_texts` VALUES ('-582', 'Bijou knows where treasures are hidden.', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '10262');
INSERT INTO `creature_ai_texts` VALUES ('-581', 'By the Light, you will leave this tomb!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '1854');
INSERT INTO `creature_ai_texts` VALUES ('-580', 'DIE, MORTALS!', null, null, null, null, null, null, null, null, '5871', '1', '0', '0', '8443');
INSERT INTO `creature_ai_texts` VALUES ('-579', 'No! You must no do this!', null, null, null, null, null, null, null, null, '0', '1', '0', '0', '8497');
INSERT INTO `creature_ai_texts` VALUES ('-578', 'Die! Die!', null, null, null, null, null, null, null, null, '5854', '1', '0', '0', '4854');
INSERT INTO `creature_ai_texts` VALUES ('-577', 'Me Grimlok, king!', null, null, null, null, null, null, null, null, '5853', '1', '0', '0', '4854');
INSERT INTO `creature_ai_texts` VALUES ('-576', 'By Thaurissan\'s beard! Slay them!', null, null, null, null, null, null, null, null, '5852', '1', '0', '0', '7291');
INSERT INTO `creature_ai_texts` VALUES ('-569', 'Aku\'mai is dead! At last, I can leave this wretched place!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '6729');
INSERT INTO `creature_ai_texts` VALUES ('-568', 'Just... Dust...', null, null, null, null, null, null, null, null, '5803', '1', '0', '0', '4832');
INSERT INTO `creature_ai_texts` VALUES ('-567', 'Sleep...', null, null, null, null, null, null, null, null, '5804', '1', '0', '0', '4832');
INSERT INTO `creature_ai_texts` VALUES ('-566', 'Who dares disturb my meditation!', null, null, null, null, null, null, null, null, '5802', '1', '0', '0', '4832');
INSERT INTO `creature_ai_texts` VALUES ('-554', 'Finally, my soul may rest... Oh, dearest Cerellean...', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '3667');
INSERT INTO `creature_ai_texts` VALUES ('-553', 'Who dares disrupt the sanctity of Eldre\'Thalas? Face me, cowards!', null, null, null, null, null, null, null, null, '0', '1', '0', '0', '11486');
INSERT INTO `creature_ai_texts` VALUES ('-552', 'Greetings citizen.', null, null, null, null, null, null, null, null, '0', '0', '7', '0', '466');
INSERT INTO `creature_ai_texts` VALUES ('-551', '%s calls for help!', null, null, null, null, null, null, null, null, '0', '2', '0', '0', '2287');
INSERT INTO `creature_ai_texts` VALUES ('-550', '%s goes into a rage after seeing a friend fall in battle!', null, null, null, null, null, null, null, null, '0', '2', '0', '0', '2287');
INSERT INTO `creature_ai_texts` VALUES ('-549', 'Guards!', null, null, null, null, null, null, null, null, '0', '1', '7', '0', 'Common Alliance Flight Master');
INSERT INTO `creature_ai_texts` VALUES ('-548', 'Arrrhhh...Guards!', null, null, null, null, null, null, null, null, '0', '1', '1', '0', 'Common Horde Flight Master');
INSERT INTO `creature_ai_texts` VALUES ('-547', 'Unknown life forms detected....assessing...', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '14224');
INSERT INTO `creature_ai_texts` VALUES ('-546', 'Target lost....resuming search patterns Delta', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '14224');
INSERT INTO `creature_ai_texts` VALUES ('-545', 'Scanning life forms....target not found', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '14224');
INSERT INTO `creature_ai_texts` VALUES ('-540', '%s is getting VERY hungry!', null, null, null, null, null, null, null, null, '0', '2', '0', '0', '8567');
INSERT INTO `creature_ai_texts` VALUES ('-539', '%s is getting hungry!', null, null, null, null, null, null, null, null, '0', '2', '0', '0', '8567');
INSERT INTO `creature_ai_texts` VALUES ('-532', 'Stop!  Foolish $c, we cannot let you summon the creature Myzrael!', null, null, null, null, null, null, null, null, '0', '1', '0', '0', '2763');
INSERT INTO `creature_ai_texts` VALUES ('-531', 'Take that!  The Drywhiskers will prevail!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'Drywhisker');
INSERT INTO `creature_ai_texts` VALUES ('-530', 'No!  Leave us!  We must not fail our task!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'Drywhisker');
INSERT INTO `creature_ai_texts` VALUES ('-529', 'Stand firm, brothers.  And don\'t worry!  Size is on our side!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'Drywhisker');
INSERT INTO `creature_ai_texts` VALUES ('-528', 'Die!  You will not free Myzrael!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'Drywhisker');
INSERT INTO `creature_ai_texts` VALUES ('-527', 'The Great One will smash you!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'Drywhisker');
INSERT INTO `creature_ai_texts` VALUES ('-526', '%s summons a Blackhand Veteran to his aid!', null, null, null, null, null, null, null, null, '0', '2', '0', '0', '10681');
INSERT INTO `creature_ai_texts` VALUES ('-525', '%s summons a Blackhand Dreadweaver to his aid!', null, null, null, null, null, null, null, null, '0', '2', '0', '0', '10680');
INSERT INTO `creature_ai_texts` VALUES ('-524', '%s begins to summon in a Blackhand Veteran!', null, null, null, null, null, null, null, null, '0', '2', '0', '0', '9080');
INSERT INTO `creature_ai_texts` VALUES ('-523', '%s begins to summon in a Blackhand Dreadweaver!', null, null, null, null, null, null, null, null, '0', '2', '0', '0', '9080');
INSERT INTO `creature_ai_texts` VALUES ('-503', 'Things are going as planned, Lord Falconcrest. I assure you, it is only a matter of time.', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '2599');
INSERT INTO `creature_ai_texts` VALUES ('-502', 'I presume you come with good news?', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '2597');
INSERT INTO `creature_ai_texts` VALUES ('-494', 'My talons will shred your puny body, $r.', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '3277');
INSERT INTO `creature_ai_texts` VALUES ('-492', 'I sense danger up ahead.', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '12337');
INSERT INTO `creature_ai_texts` VALUES ('-491', 'If I should fall, take my pouch. Make certain that it gets to the High General.', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '12337');
INSERT INTO `creature_ai_texts` VALUES ('-490', 'My back is killing me.', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '12337');
INSERT INTO `creature_ai_texts` VALUES ('-473', '%s is reduced to rubble, but still continues to fight.', null, null, null, null, null, null, null, null, '0', '2', '0', '0', '2359');
INSERT INTO `creature_ai_texts` VALUES ('-472', '%s\'s strength dwindles as chunks of rock break off.', null, null, null, null, null, null, null, null, '0', '2', '0', '0', '2359');
INSERT INTO `creature_ai_texts` VALUES ('-471', '%s begins to crack and break apart.', null, null, null, null, null, null, null, null, '0', '2', '0', '0', '2359');
INSERT INTO `creature_ai_texts` VALUES ('-470', 'You have my word that I shall find a use for your body after I\'ve killed you, $r.', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '2733');
INSERT INTO `creature_ai_texts` VALUES ('-469', 'You will never stop the Forsaken, $r. The Dark Lady shall make you suffer.', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '2733');
INSERT INTO `creature_ai_texts` VALUES ('-462', 'The Council of Duskwood must take action.  Evil lingers in the air.', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '269');
INSERT INTO `creature_ai_texts` VALUES ('-461', 'Aber?  Is that you...?  Oh...I\'m so hungry, Aber!  SO HUNGRY!!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '314');
INSERT INTO `creature_ai_texts` VALUES ('-460', 'Wait...you are not my husband.  But he must have sent you.  And you...look..delicious!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '314');
INSERT INTO `creature_ai_texts` VALUES ('-459', 'Undead are crawling all over the land.  Where is the Stormwind Army?', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '263');
INSERT INTO `creature_ai_texts` VALUES ('-458', 'The people of Darkshire expect more from the Council.  We cannot let them suffer from this unholy wrath which plagues us.', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '269');
INSERT INTO `creature_ai_texts` VALUES ('-457', 'Our cause falls on deaf ears beyond the thick, stone walls of Stormwind.', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '271');
INSERT INTO `creature_ai_texts` VALUES ('-456', 'I fear something dark is coming.', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '325');
INSERT INTO `creature_ai_texts` VALUES ('-455', 'We need better representation from Stormwind. Our homes are falling to the undead.', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '270');
INSERT INTO `creature_ai_texts` VALUES ('-454', 'Constant bickering will get us nowhere.  We need to take action.', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '269');
INSERT INTO `creature_ai_texts` VALUES ('-453', 'The news from Stormwind does not bode well. . . .', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '271');
INSERT INTO `creature_ai_texts` VALUES ('-452', 'The light appears to have forsaken us.', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '325');
INSERT INTO `creature_ai_texts` VALUES ('-451', 'Why haven\'t the Stormwind guards come?', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '325');
INSERT INTO `creature_ai_texts` VALUES ('-450', 'Toil not in matters of the past, $N!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '2044');
INSERT INTO `creature_ai_texts` VALUES ('-449', 'Who is this mere $r that meddles with that which is past?  May the legend of Stalvan die along with you!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '2044');
INSERT INTO `creature_ai_texts` VALUES ('-448', '%s lets out a shrill cry.', null, null, null, null, null, null, null, null, '0', '2', '0', '0', '10506');
INSERT INTO `creature_ai_texts` VALUES ('-438', 'We are betrayed!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '10433');
INSERT INTO `creature_ai_texts` VALUES ('-437', 'I\'ll stay behind and guard the wreck. Hurry! Hopefully no one will notice the smoke...', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '3451');
INSERT INTO `creature_ai_texts` VALUES ('-436', 'Looks like you\'ll have to go ahead to Ratchet and tell Sputtervalve that I\'ve wrecked the shredder.', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '3451');
INSERT INTO `creature_ai_texts` VALUES ('-435', 'Now this is an example of what not to summon. Look, it\'s frail and brittle. One good whack from a mace will send bone shards flying.', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '11582');
INSERT INTO `creature_ai_texts` VALUES ('-434', 'I wanna see the Mage Tower.', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '3504');
INSERT INTO `creature_ai_texts` VALUES ('-433', 'Where we goin\'?', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '3504');
INSERT INTO `creature_ai_texts` VALUES ('-432', 'Why do we always go the same way?', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '3504');
INSERT INTO `creature_ai_texts` VALUES ('-431', 'Is it true? Are there crocolisks in the canal?', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '3504');
INSERT INTO `creature_ai_texts` VALUES ('-430', 'My feet hurt.', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '3504');
INSERT INTO `creature_ai_texts` VALUES ('-429', 'Are we there yet?', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '3504');
INSERT INTO `creature_ai_texts` VALUES ('-428', 'O\'ourse I\'m talking to myself. Only way to get a decent conversation in this city.', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '3520');
INSERT INTO `creature_ai_texts` VALUES ('-427', 'As if I don\'t have better things to do in my old age than carry buckets of water.', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '3520');
INSERT INTO `creature_ai_texts` VALUES ('-426', 'Where\'s the water Emma? Get the water Emma? If\'n it weren\'t fer me that lot wouldn\'t know what water looks like.', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '3520');
INSERT INTO `creature_ai_texts` VALUES ('-425', 'Seems like a hundred times a day I walk all the way to get more water. No respect for their elders I tell ya.', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '3520');
INSERT INTO `creature_ai_texts` VALUES ('-424', 'Jack and Jill my wrinkled patoot! I do all the water luggin\' \'round here.', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '3520');
INSERT INTO `creature_ai_texts` VALUES ('-423', 'Think I\'m starting to wear a rut in the paving stones.', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '3520');
INSERT INTO `creature_ai_texts` VALUES ('-416', 'All of a sudden they were everywhere.', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '1719');
INSERT INTO `creature_ai_texts` VALUES ('-415', 'They must have had someone helping them.', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '1719');
INSERT INTO `creature_ai_texts` VALUES ('-414', 'If the Captain finds out, it\'ll be the end of me.', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '1719');
INSERT INTO `creature_ai_texts` VALUES ('-413', 'It\'s all their fault, stupid Alliance army. Just had to build their towers right behind my farm.', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '1395');
INSERT INTO `creature_ai_texts` VALUES ('-412', 'Spare some change for a poor blind man?...What do you mean I\'m not blind?...I\'M NOT BLIND! I CAN SEE! ITS A MIRACLE!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '1395');
INSERT INTO `creature_ai_texts` VALUES ('-411', 'I will gladly pay you Tuesday for a hamburger today.', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '1395');
INSERT INTO `creature_ai_texts` VALUES ('-410', 'Hmmm, this one looks like something that would be better off as a windchime. Take notes class... This is NOT what you want to summon in the heat of battle.', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '11582');
INSERT INTO `creature_ai_texts` VALUES ('-409', 'Get those parts moving down to the ship!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '1763');
INSERT INTO `creature_ai_texts` VALUES ('-408', 'Anyone want to take a break?  Well too bad!  Get to work you oafs!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '1763');
INSERT INTO `creature_ai_texts` VALUES ('-407', 'I shall spill your blood, $c!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '315');
INSERT INTO `creature_ai_texts` VALUES ('-406', 'Never cross a Dark Iron, $c.', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '1169');
INSERT INTO `creature_ai_texts` VALUES ('-405', '%s seems much calmer now that it has eaten the remains of $N.', null, null, null, null, null, null, null, null, '0', '2', '0', '0', '2931');
INSERT INTO `creature_ai_texts` VALUES ('-404', 'I cannot permit you to enter the temple! I must destroy you for your own good!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'Common Green Dragon Text');
INSERT INTO `creature_ai_texts` VALUES ('-388', 'Hearty Kill!', null, null, null, null, null, null, null, null, '5801', '1', '0', '0', '4831');
INSERT INTO `creature_ai_texts` VALUES ('-377', '[Orcish] Tago mog regas gi mog Tov\'nokaz Kagg', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'Orc Common Text');
INSERT INTO `creature_ai_texts` VALUES ('-376', '[Orcish] Ogg kaz ko zugas kil mog Tov\'nokaz Kagg', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'Orc Common Text');
INSERT INTO `creature_ai_texts` VALUES ('-375', '%s\'s eyes glow red as he lights his dynamite and begins to cackle madly!', null, null, null, null, null, null, null, null, '0', '2', '0', '0', '1222');
INSERT INTO `creature_ai_texts` VALUES ('-374', '[Dwarvish] Dum mos', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '2149');
INSERT INTO `creature_ai_texts` VALUES ('-373', 'Die in the name of Ragnaros!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '1222');
INSERT INTO `creature_ai_texts` VALUES ('-372', 'The Loch belongs to the Stonesplinter Tribe now, $N! Now die!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '1399');
INSERT INTO `creature_ai_texts` VALUES ('-371', 'Die $r! These lands belong to the Stonesplinter Tribe!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '1399');
INSERT INTO `creature_ai_texts` VALUES ('-370', 'A $c called $N? You\'ll make a fine breakfast!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '1205');
INSERT INTO `creature_ai_texts` VALUES ('-369', 'Bash it!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '1210');
INSERT INTO `creature_ai_texts` VALUES ('-368', 'Dat $r look gud to eat!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '1210');
INSERT INTO `creature_ai_texts` VALUES ('-367', 'Huh? What dat?', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '1210');
INSERT INTO `creature_ai_texts` VALUES ('-366', 'ARRRRRRR!', null, null, null, null, null, null, null, null, '0', '1', '0', '0', '13602');
INSERT INTO `creature_ai_texts` VALUES ('-365', 'I tire of this nonsense! Prepare to die!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '2318');
INSERT INTO `creature_ai_texts` VALUES ('-364', 'Wahehe! I\'m taking you down with me!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '1222');
INSERT INTO `creature_ai_texts` VALUES ('-363', 'The Thandol Span fell to Ragnaros. So shall the Stonewrought Dam!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '1222');
INSERT INTO `creature_ai_texts` VALUES ('-362', 'King Magni Bronzebeard is a fool and a charlatan!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '1222');
INSERT INTO `creature_ai_texts` VALUES ('-361', 'Raaar!!! Me smash $r!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'Ogre Common Text');
INSERT INTO `creature_ai_texts` VALUES ('-360', 'Me smash! You die!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'Ogre Common Text');
INSERT INTO `creature_ai_texts` VALUES ('-359', 'I\'ll crush you!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'Ogre Common Text');
INSERT INTO `creature_ai_texts` VALUES ('-358', 'Time to die, $c!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '1169');
INSERT INTO `creature_ai_texts` VALUES ('-357', 'Feel the power of the Dark Iron Dwarves!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '1169');
INSERT INTO `creature_ai_texts` VALUES ('-356', 'Weak $c! You are no match for the Stonesplinter Tribe!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '1205 and 1399');
INSERT INTO `creature_ai_texts` VALUES ('-355', 'The only good $r is a dead $r!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '1205');
INSERT INTO `creature_ai_texts` VALUES ('-354', 'Yip! Me kill!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'Trogg Common Text');
INSERT INTO `creature_ai_texts` VALUES ('-353', 'Me no run from $c like you!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'Trogg Common Text');
INSERT INTO `creature_ai_texts` VALUES ('-346', '%s begins to summon in reinforcements!', null, null, null, null, null, null, null, null, '0', '2', '0', '0', '2358');
INSERT INTO `creature_ai_texts` VALUES ('-345', '%s\'s death cry has stirred the nearby silithid hive.', null, null, null, null, null, null, null, null, '0', '2', '0', '0', 'Tortured Druid/Sentinel death');
INSERT INTO `creature_ai_texts` VALUES ('-344', '%s faces southeast and whimpers before looking back at you. ', null, null, null, null, null, null, null, null, '0', '2', '0', '0', '3695');
INSERT INTO `creature_ai_texts` VALUES ('-343', '%s growls in your direction before taking time to sniff you.', null, null, null, null, null, null, null, null, '0', '2', '0', '0', '3695');
INSERT INTO `creature_ai_texts` VALUES ('-342', '%s calls more of his allies out of the shadows.', null, null, null, null, null, null, null, null, '0', '2', '0', '0', '639');
INSERT INTO `creature_ai_texts` VALUES ('-341', '%s jumps out of the shadows!', null, null, null, null, null, null, null, null, '0', '2', '0', '0', '636');
INSERT INTO `creature_ai_texts` VALUES ('-324', 'Time to bash!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '1119');
INSERT INTO `creature_ai_texts` VALUES ('-323', 'So ju weh siame is fus nehjo skam worl Uptfeel', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '1260');
INSERT INTO `creature_ai_texts` VALUES ('-322', 'Dim wha Siame cyaa fi so yudo', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'Common Frostmane Troll Text');
INSERT INTO `creature_ai_texts` VALUES ('-321', 'Iman m t\'ief fu Fus\'obeah italaf', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'Common Frostmane Troll Text');
INSERT INTO `creature_ai_texts` VALUES ('-320', 'Sands consume you!', null, null, null, null, null, null, null, null, '5872', '1', '14', '0', '7271');
INSERT INTO `creature_ai_texts` VALUES ('-311', 'This one is slightly better than the last. However, it still suffers from the same flimsy bone structure as the others. When you summon one of these, you are on the right path.', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '11582');
INSERT INTO `creature_ai_texts` VALUES ('-274', '%s looks weak enough to capture.', null, null, null, null, null, null, null, null, '0', '2', '0', '0', '4351');
INSERT INTO `creature_ai_texts` VALUES ('-233', 'So much to do, so much to do! Where does the time go?', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '295');
INSERT INTO `creature_ai_texts` VALUES ('-232', 'The Brotherhood will not be hampered by insects.', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '6846');
INSERT INTO `creature_ai_texts` VALUES ('-231', 'I\'ll cut you!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'Common Frostmane Troll Text');
INSERT INTO `creature_ai_texts` VALUES ('-230', 'You be dead soon!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'Common Frostmane Troll Text');
INSERT INTO `creature_ai_texts` VALUES ('-229', 'Killing you be easy.', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'Common Frostmane Troll Text');
INSERT INTO `creature_ai_texts` VALUES ('-228', 'I gonna make you into mojo!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'Common Frostmane Troll Text');
INSERT INTO `creature_ai_texts` VALUES ('-215', 'Destroy!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'Trogg Common Text');
INSERT INTO `creature_ai_texts` VALUES ('-214', 'Kill!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'Trogg Common Text');
INSERT INTO `creature_ai_texts` VALUES ('-213', 'Crush!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'Trogg Common Text');
INSERT INTO `creature_ai_texts` VALUES ('-212', 'Aaaahhhhhh!', null, null, null, null, null, null, null, null, '5873', '1', '0', '0', '7271');
INSERT INTO `creature_ai_texts` VALUES ('-211', 'Die in the name of Edwin van Cleef!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'Defias Messenger');
INSERT INTO `creature_ai_texts` VALUES ('-210', 'I\'ll deliver you, weak $c, to the afterlife!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'Defias Messenger');
INSERT INTO `creature_ai_texts` VALUES ('-209', 'I have a special message for $n. And it says you must die!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'Defias Messenger');
INSERT INTO `creature_ai_texts` VALUES ('-208', 'Some coin?', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '1402,1405');
INSERT INTO `creature_ai_texts` VALUES ('-207', 'Help a poor bloke out?', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '1402,1405');
INSERT INTO `creature_ai_texts` VALUES ('-206', 'Shine yer armor for a copper?', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '1402,1405');
INSERT INTO `creature_ai_texts` VALUES ('-205', 'Freshly baked bread for sale!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '3518');
INSERT INTO `creature_ai_texts` VALUES ('-204', 'Fresh bread for sale!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '3518');
INSERT INTO `creature_ai_texts` VALUES ('-203', 'NO!!!  It puts the tannin in the basket, or it gets the mallet again!', null, null, null, null, null, null, null, null, '0', '1', '0', '0', '14351');
INSERT INTO `creature_ai_texts` VALUES ('-202', 'A fine trophy your head will make, $r.', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '2015,2017,2018');
INSERT INTO `creature_ai_texts` VALUES ('-201', 'My talons will shred your puny body, $r.', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '2018');
INSERT INTO `creature_ai_texts` VALUES ('-200', 'You will be easy prey, $c.', null, null, null, null, null, null, null, null, '0', '1', '0', '0', '2015,2017,2018');
INSERT INTO `creature_ai_texts` VALUES ('-198', 'You should not be here! Slay them!', null, null, null, null, null, null, null, null, '5799', '1', '0', '0', '4831');
INSERT INTO `creature_ai_texts` VALUES ('-197', 'We can make it better, stronger, faster. We have the technology. We have the magic.', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '2922');
INSERT INTO `creature_ai_texts` VALUES ('-196', 'It is dangerous here, master. But I shall help stand guard.', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '2922');
INSERT INTO `creature_ai_texts` VALUES ('-195', 'Brzt... click... whir...', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '2922');
INSERT INTO `creature_ai_texts` VALUES ('-194', 'One day I\'ll be a real boy.', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '2922');
INSERT INTO `creature_ai_texts` VALUES ('-193', 'Gizmos... check. Doothingies... check. Wizzers... check.', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '2922');
INSERT INTO `creature_ai_texts` VALUES ('-192', 'It can get really hot here in the Badlands. But at least it\'s a dry heat.', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '2922');
INSERT INTO `creature_ai_texts` VALUES ('-191', 'The troggs...they never stop coming.  Die trogg!  Die!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'Common Leprous Say');
INSERT INTO `creature_ai_texts` VALUES ('-190', 'No gnome will be left behind.', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'Common Leprous Say');
INSERT INTO `creature_ai_texts` VALUES ('-189', 'This sickness clouds my vision, but I know you must be a trogg.  Die foul invader!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'Common Leprous Say');
INSERT INTO `creature_ai_texts` VALUES ('-188', 'A foul trogg if ever I saw one.  Die!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'Common Leprous Say');
INSERT INTO `creature_ai_texts` VALUES ('-186', 'The living are here!', null, null, null, null, null, null, null, null, '6596', '1', '0', '0', '10411');
INSERT INTO `creature_ai_texts` VALUES ('-185', 'Confess and we shall set you free.', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '4306');
INSERT INTO `creature_ai_texts` VALUES ('-184', 'You will talk eventually. You might as well spill it now.', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '4306');
INSERT INTO `creature_ai_texts` VALUES ('-183', 'What? Oh no. I don\'t care what you have to say. I just enjoy inflicting pain.', null, null, null, null, null, null, null, null, '0', '1', '0', '0', '4306');
INSERT INTO `creature_ai_texts` VALUES ('-182', 'Mine! Mine! Mine! Gizlock is the ruler of this domain! You shall never reveal my presence!', null, null, null, null, null, null, null, null, '0', '1', '0', '0', '13601');
INSERT INTO `creature_ai_texts` VALUES ('-178', 'Looking for these???? You\'ll never have em!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '11058');
INSERT INTO `creature_ai_texts` VALUES ('-177', 'I\'m going to wear your skin as a smoking jacket! The stogies? You\'ll have to pry them from my cold dead... er... RAWR!!!!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '11058');
INSERT INTO `creature_ai_texts` VALUES ('-176', 'D\'ah! Now you\'re making me angry!', null, null, null, null, null, null, null, null, '5779', '0', '0', '0', '646');
INSERT INTO `creature_ai_texts` VALUES ('-175', 'You land lovers are tougher then I thought! I will need to improvise', null, null, null, null, null, null, null, null, '5778', '0', '0', '0', '646');
INSERT INTO `creature_ai_texts` VALUES ('-174', 'We\'re under attack! Avast ya swabs! Repel the invaders!', null, null, null, null, null, null, null, null, '5777', '1', '0', '0', '646');
INSERT INTO `creature_ai_texts` VALUES ('-173', 'The Brotherhood shall prevail!', null, null, null, null, null, null, null, null, '5784', '1', '0', '0', '639');
INSERT INTO `creature_ai_texts` VALUES ('-172', 'Fools! Our cause is righteous!', null, null, null, null, null, null, null, null, '5783', '1', '0', '0', '639');
INSERT INTO `creature_ai_texts` VALUES ('-171', 'Lapdogs, all of you!', null, null, null, null, null, null, null, null, '5782', '1', '0', '0', '639');
INSERT INTO `creature_ai_texts` VALUES ('-170', 'And stay down!', null, null, null, null, null, null, null, null, '5781', '1', '0', '0', '639');
INSERT INTO `creature_ai_texts` VALUES ('-169', 'None may challenge the Brotherhood!', null, null, null, null, null, null, null, null, '5780', '1', '0', '0', '639');
INSERT INTO `creature_ai_texts` VALUES ('-168', 'Who dares disturb me?  Die $N!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '315');
INSERT INTO `creature_ai_texts` VALUES ('-167', 'KILL!!!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '3569');
INSERT INTO `creature_ai_texts` VALUES ('-166', 'Soon, the Scourge will rule the world!', null, null, null, null, null, null, null, null, '5821', '1', '0', '0', '7357');
INSERT INTO `creature_ai_texts` VALUES ('-165', 'We will spread across this barren land!', null, null, null, null, null, null, null, null, '5820', '1', '0', '0', '7357');
INSERT INTO `creature_ai_texts` VALUES ('-164', 'We will enslave the quilboar!', null, null, null, null, null, null, null, null, '5819', '1', '0', '0', '7357');
INSERT INTO `creature_ai_texts` VALUES ('-163', 'Slay them, my brethren! For the Scourge!', null, null, null, null, null, null, null, null, '5822', '1', '0', '0', '7357');
INSERT INTO `creature_ai_texts` VALUES ('-162', 'Mmm... I love my delicious Southshore stout.', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '2440');
INSERT INTO `creature_ai_texts` VALUES ('-161', 'A living $r... soon to be a dead like me.', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'Common Undead Text');
INSERT INTO `creature_ai_texts` VALUES ('-148', '[Kalimag] Ma reth bromo zoln kilagrin dra ma zoern tu ko fraht ko kadrom Ma krin drinor zoln drinor Ma krin kan aasrugel korsul', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '8666');
INSERT INTO `creature_ai_texts` VALUES ('-144', 'What? How dare you!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '1754');
INSERT INTO `creature_ai_texts` VALUES ('-143', 'The Defias shall succeed! No meek adventurer will stop us!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '1755');
INSERT INTO `creature_ai_texts` VALUES ('-142', 'Get it while it\'s hot!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '3518');
INSERT INTO `creature_ai_texts` VALUES ('-140', 'The coils of death... Will crush you.', null, null, null, null, null, null, null, null, '5787', '1', '0', '0', '3670');
INSERT INTO `creature_ai_texts` VALUES ('-137', 'I will be reborn, mortals! Incendius shall raise me from these ashes!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '9026');
INSERT INTO `creature_ai_texts` VALUES ('-136', 'Bah! My power rules here!', null, null, null, null, null, null, null, null, '5816', '1', '0', '0', '4421');
INSERT INTO `creature_ai_texts` VALUES ('-135', 'You outsiders will pay for encroaching on our land!', null, null, null, null, null, null, null, null, '5815', '1', '0', '0', '4421');
INSERT INTO `creature_ai_texts` VALUES ('-134', 'Our new allies  will avenge us!', null, null, null, null, null, null, null, null, '5814', '1', '0', '0', '4421');
INSERT INTO `creature_ai_texts` VALUES ('-133', 'Troublesome whelps. I\'ll teach you to interfere!', null, null, null, null, null, null, null, null, '5813', '1', '0', '0', '4421');
INSERT INTO `creature_ai_texts` VALUES ('-123', 'I am the serpent king! I can do anything.', null, null, null, null, null, null, null, null, '5788', '1', '0', '0', '3673');
INSERT INTO `creature_ai_texts` VALUES ('-106', '%s goes into a frenzy!', null, null, null, null, null, null, null, null, '0', '2', '0', '0', 'Enrage Text');
INSERT INTO `creature_ai_texts` VALUES ('-105', 'Your bones will break under my boot, $r!', null, null, null, null, null, null, null, null, '0', '0', '1', '0', '2108');
INSERT INTO `creature_ai_texts` VALUES ('-104', 'This land belongs to the Dark Iron Dwarves. Prepare to see the afterlife, $c!', null, null, null, null, null, null, null, null, '0', '0', '6', '0', '1364');
INSERT INTO `creature_ai_texts` VALUES ('-103', 'Brains...', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '1158');
INSERT INTO `creature_ai_texts` VALUES ('-102', 'Long live the Dragonmaw! Die you worthless $r!', null, null, null, null, null, null, null, null, '0', '0', '1', '0', 'Common Dragonmaw Text');
INSERT INTO `creature_ai_texts` VALUES ('-101', 'For the Dragonmaw!', null, null, null, null, null, null, null, null, '0', '0', '1', '0', 'Common Dragonmaw Text');
INSERT INTO `creature_ai_texts` VALUES ('-100', '%s lets out a high pitched screech, calling for help!', null, null, null, null, null, null, null, null, '0', '2', '0', '0', '1021');
INSERT INTO `creature_ai_texts` VALUES ('-99', 'You will never wake the dreamer!', null, null, null, null, null, null, null, null, '5785', '1', '0', '0', '3669');
INSERT INTO `creature_ai_texts` VALUES ('-74', 'Aaaaahhh! So close to escaping.', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'Common Gnome Text');
INSERT INTO `creature_ai_texts` VALUES ('-73', 'So dark...', null, null, null, null, null, null, null, null, '0', '0', '0', '1', '11936');
INSERT INTO `creature_ai_texts` VALUES ('-47', '%s attempts to run away in fear!', null, null, null, null, null, null, null, null, '0', '2', '0', '0', 'Common Text');
INSERT INTO `creature_ai_texts` VALUES ('-46', '%s becomes enraged!', null, null, null, null, null, null, null, null, '0', '2', '0', '0', 'Common Text');
INSERT INTO `creature_ai_texts` VALUES ('-42', 'Time to join us, $c.', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '1157');
INSERT INTO `creature_ai_texts` VALUES ('-33', 'Warning! Warning! Intruder alert! Intruder alert!', null, null, null, null, null, null, null, null, '0', '1', '0', '0', '7849');
INSERT INTO `creature_ai_texts` VALUES ('-32', 'Electric justice!', null, null, null, null, null, null, null, null, '5811', '1', '0', '0', '6235');
INSERT INTO `creature_ai_texts` VALUES ('-31', '%s is splashed by the blood and becomes irradiated!', null, null, null, null, null, null, null, null, '0', '2', '0', '0', 'Common Gnomeregan Emote');
INSERT INTO `creature_ai_texts` VALUES ('-30', '%s blood sprays into the air!', null, null, null, null, null, null, null, null, '0', '2', '0', '0', 'Common Gnomeregan Emote');
INSERT INTO `creature_ai_texts` VALUES ('-29', 'You no challenge me, scrubs! I\'m da king now, and I stay king FOREVER!!!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '11501');
INSERT INTO `creature_ai_texts` VALUES ('-28', 'You do not belong here!  Ancients, rise against these intruders!', null, null, null, null, null, null, null, null, '0', '1', '0', '0', '11489');
INSERT INTO `creature_ai_texts` VALUES ('-22', 'VanCleef pay big for you heads!', null, null, null, null, null, null, null, null, '5774', '1', '0', '0', '644');
INSERT INTO `creature_ai_texts` VALUES ('-18', 'For Victory! For Agamaggan!', null, null, null, null, null, null, null, null, '5812', '1', '0', '0', '4420');
INSERT INTO `creature_ai_texts` VALUES ('-8', 'Yiieeeee! Me run!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'Common Kobold Text');
INSERT INTO `creature_ai_texts` VALUES ('-7', 'You no take candle!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'Common Kobold Text');
INSERT INTO `creature_ai_texts` VALUES ('-6', 'Grrrr... fresh meat!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'Common Gnoll Text');
INSERT INTO `creature_ai_texts` VALUES ('-5', 'More bones to gnaw on...', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'Common Gnoll Text');
INSERT INTO `creature_ai_texts` VALUES ('-4', 'Feel the power of the Brotherhood!', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'Common Defias Text');
INSERT INTO `creature_ai_texts` VALUES ('-3', 'Ah, a chance to use this freshly sharpened blade.', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'Common Defias Text');
INSERT INTO `creature_ai_texts` VALUES ('-2', 'The Brotherhood will not tolerate your actions.', null, null, null, null, null, null, null, null, '0', '0', '0', '0', 'Common Defias Text');
INSERT INTO `creature_ai_texts` VALUES ('-1', 'I see those fools at the Abbey sent some fresh meat for us.', null, null, null, null, null, null, null, null, '0', '0', '0', '0', '103');
